import type {
  Candle,
  Commodity,
  ExchangeMarket,
  IndexMetric,
  InputCostPoint,
  PricePoint,
  TickerItem,
} from '@/types';

// Seedlenmiş sözde rastgele üretici — tutarlı mock seriler için
function seeded(seed: number) {
  let s = seed;
  return () => {
    s = (s * 9301 + 49297) % 233280;
    return s / 233280;
  };
}

function makeSeries(seed: number, len: number, base: number, vol: number): number[] {
  const rnd = seeded(seed);
  const out: number[] = [];
  let v = base;
  const trendBias = ((seed % 100) / 100 - 0.4) * vol * 0.1;
  for (let i = 0; i < len; i++) {
    v += (rnd() - 0.45) * vol + trendBias;
    v = Math.max(base * 0.6, v);
    out.push(Number(v.toFixed(2)));
  }
  return out;
}

// Tarihli fiyat + hacim serisi — Recharts interaktif grafiği için
function makeDatedSeries(seed: number, days: number, base: number, vol: number): PricePoint[] {
  const prices = makeSeries(seed, days, base, vol);
  const rnd = seeded(seed + 1000);
  const today = new Date('2026-07-24');
  return prices.map((price, i) => {
    const d = new Date(today);
    d.setDate(today.getDate() - (days - 1 - i));
    return {
      date: d.toISOString().slice(0, 10),
      price,
      volume: Math.round(base * (800 + rnd() * 600)),
    };
  });
}

// OHLC mum verisi — teknik analiz grafiği için (iş günü bazlı)
function makeCandles(seed: number, count: number, base: number, vol: number): Candle[] {
  const rnd = seeded(seed);
  const today = new Date('2026-07-24');
  const candles: Candle[] = [];
  let prevClose = base;
  // Ürüne özgü trend eğilimi — seed'den deterministik olarak türetilir
  const trendBias = ((seed % 100) / 100 - 0.4) * vol * 0.15;
  // Mevsimsel dalgalanma — hasat dönemlerinde fiyat hareketi
  const seasonalAmp = vol * (0.5 + (seed % 7) * 0.1);
  for (let i = 0; i < count; i++) {
    const d = new Date(today);
    d.setDate(today.getDate() - (count - 1 - i));
    const seasonal = Math.sin((i / count) * Math.PI * 2 + (seed % 10)) * seasonalAmp;
    const drift = (rnd() - 0.48) * vol + trendBias + seasonal * 0.3;
    const open = prevClose;
    const close = Math.max(base * 0.5, open + drift);
    const wick = Math.abs(drift) * (0.8 + rnd() * 1.2);
    const high = Math.max(open, close) + wick * rnd();
    const low = Math.max(base * 0.4, Math.min(open, close) - wick * rnd());
    const volume = Math.round(base * (800 + rnd() * 800) * (1 + Math.abs(seasonal) * 0.2));
    candles.push({
      date: d.toISOString().slice(0, 10),
      open: Number(open.toFixed(2)),
      high: Number(high.toFixed(2)),
      low: Number(low.toFixed(2)),
      close: Number(close.toFixed(2)),
      volume,
    });
    prevClose = close;
  }
  return candles;
}

// Commodity ID'den deterministik seed üretir — her ürünün grafiği benzersiz olur
function hashIdToSeed(id: string): number {
  let hash = 0;
  for (let i = 0; i < id.length; i++) {
    hash = ((hash << 5) - hash + id.charCodeAt(i)) | 0;
  }
  return Math.abs(hash) + 1;
}

// Teknik analiz sayfası için sembol listesi — ürünler + endeksler (dosya sonunda tanımlı)
export interface TaSymbol {
  id: string;
  name: string;
  category: string;
  unit: string;
  candles: Candle[];
}

function changeFrom(series: number[], offset: number): number {
  if (series.length <= offset) return 0;
  const prev = series[series.length - 1 - offset];
  const cur = series[series.length - 1];
  return ((cur - prev) / prev) * 100;
}

// ── Ticker Bandı ──────────────────────────────────────────────
export const tickerItems: TickerItem[] = [
  { name: 'Buğday', price: 16.5, unit: '₺/kg', changePct: 1.32 },
   { name: 'Elma', price: 57.68, unit: '₺/kg', changePct: 1.47 },
   { name: 'Aspir', price: 39.5, unit: '₺/kg', changePct: -1.20 },
   { name: 'Tritikale', price: 12.83, unit: '₺/kg', changePct: 1.00 },
   { name: 'Pirinç', price: 98.3, unit: '₺/kg', changePct: 2.17 },
   { name: 'Darı', price: 14.75, unit: '₺/kg', changePct: 0.2 },
  { name: 'Arpa', price: 12.75, unit: '₺/kg', changePct: -0.78 },
  { name: 'Kuru fasulye', price: 52.50, unit: '₺/kg', changePct: 1.8 },
  { name: 'Pamuk', price: 29.8, unit: '₺/kg', changePct: 2.41 },
  { name: 'Mısır', price: 7.85, unit: '₺/kg', changePct: 0.56 },
  { name: 'Ayçiçeği', price: 34.2, unit: '₺/kg', changePct: -1.14 },
  { name: 'Süt', price: 24.30, unit: '₺/lt', changePct: 0.88 },
   { name: 'Yulaf', price: 13.40, unit: '₺/kg', changePct: 0.90 },
   { name: 'Kahve', price: 420.50, unit: '₺/kg', changePct: 0.50 },
  { name: 'Mısır', price: 12.45, unit: '₺/kg', changePct: 0.67 },
  { name: 'Çeltik', price: 36.94, unit: '₺/kg', changePct: 0.50 },
   { name: 'Çavdar', price: 12.50, unit: '₺/kg', changePct: 1.12 },
   { name: 'Soya Küspesi', price: 15.02, unit: '₺/kg', changePct: 0.85 },
   { name: 'Soya Yağı', price: 60.61, unit: '₺/kg', changePct: 0.64 },
   { name: 'Palm Yağı', price: 51.044, unit: '₺/kg', changePct: 0.87 },
   { name: 'Çay', price:  35.00, unit: '₺/kg', changePct: 0.12 },
   { name: 'Tütün', price: 305, unit: '₺/kg', changePct: 0.26 },
   { name: 'Şeker Pancarı', price: 36.23, unit: '₺/kg', changePct: -0.14 },
   { name: 'Kuru Fasulye,', price: 46, unit: '₺/kg', changePct: 0.36 },
   { name: 'Nohut', price: 41.50, unit: '₺/kg', changePct: 0.15 },
   { name: 'Mercimek', price: 35.10, unit: '₺/kg', changePct: 0.26 },
   { name: 'Bezelye', price: 90.00, unit: '₺/kg', changePct: 0.66 },
  { name: 'Bakla', price: 49.60, unit: '₺/kg', changePct: 6.4 },
  { name: 'Beze', price: 36.01, unit: '₺/kg', changePct: -3.0 },
    { name: 'Börülce', price: 81.93, unit: '₺/kg', changePct: -8.8 },
    { name: 'Burçak', price: 113.74 , unit: '₺/kg', changePct: 2.17 },
  { name: 'Susam', price: 98.90 , unit: '₺/kg', changePct: 2.50 },
  { name: 'Keten Tohumu', price: 75.50 , unit: '₺/kg', changePct: 1.00 },
  { name: 'Çiğit', price: 13.70 , unit: '₺/kg', changePct: 2.45 },
  { name: 'Yer Fıstığı', price: 159.42 , unit: '₺/kg', changePct: 4.2 },
  { name: 'Patates', price: 29.30 , unit: '₺/kg', changePct: -2.2 },
  { name: 'Kuru Soğan', price: 35.20 , unit: '₺/kg', changePct: 4.2 },
  { name: 'Sarımsak', price: 118.56 , unit: '₺/kg', changePct: -3.1 },
  { name: 'Yer Elması', price: 17.50 , unit: '₺/kg', changePct: 0.00 },
  { name: 'Kereviz', price: 52.25 , unit: '₺/kg', changePct: -2.2 },
  { name: 'Kenevir', price: 220.00 , unit: '₺/kg', changePct: 1.50 },
  { name: 'Haşhaş', price: 165.50 , unit: '₺/kg', changePct: 1.7 },
  { name: 'Şerbetçiotu', price: 200.00 , unit: '₺/kg', changePct: 0.00 },
  { name: 'Korunga', price: 62.00 , unit: '₺/kg', changePct: 4.2 },
  { name: 'Fiğ', price: 30.0 , unit: '₺/kg', changePct: 2.8 },
{ name: 'Silajlık Mısır', price: 4.42 , unit: '₺/kg', changePct: -1.2 },
  { name: 'Sorgum', price: 93.00 , unit: '₺/kg', changePct: 0.4 },
  { name: 'Yemlik Pancar', price: 5.00 , unit: '₺/kg', changePct: 3.5 },
{ name: 'Sivri Biber', price: 34.45 , unit: '₺/kg', changePct: 4.8 },
{ name: 'Patlıcan', price: 25.00 , unit: '₺/kg', changePct: -2.3 },
{ name: 'Kabak', price: 28.46 , unit: '₺/kg', changePct: -23.7 },
  { name: 'Ispanak', price: 42.35 , unit: '₺/kg', changePct: -5.8 },
  { name: 'Pırasa', price: 30.5 , unit: '₺/kg', changePct: -4.0  },
   { name: 'Pazı', price: 18.50 , unit: '₺/kg', changePct: 1.0 },
   { name: 'Armut', price: 54.0, unit: '₺/kg', changePct: 3.2 },
   { name: 'Kiraz:', price: 90.00 , unit: '₺/kg', changePct: 8.3 },
   { name: 'Vişne', price: 60.50 , unit: '₺/kg', changePct: -4.1 },
   { name: 'Portakal', price: 34.45 , unit: '₺/kg', changePct: 14.2 },
   { name: 'Mandalina', price: 50.40 , unit: '₺/kg', changePct: 5.00 },
   { name: 'Limon', price: 44.30  , unit: '₺/kg', changePct: -6.7 },
   { name: 'Greyfurt', price: 45.45 , unit: '₺/kg', changePct: 1.1 },
   { name: 'Çilek', price: 100.50 , unit: '₺/kg', changePct: 9.4 },
   { name: 'İncir', price: 120 , unit: '₺/kg', changePct: -18.2 },
   { name: 'Dut', price: 70.00  , unit: '₺/kg', changePct: -42.00 },
   { name: 'Fındık (Kabuklu)', price: 140.00 , unit: '₺/kg', changePct: 3.8 },
   { name: 'Ceviz (Kabuklu)', price: 160.00 , unit: '₺/kg', changePct: 1.2 },
   { name: 'Badem (Kabuklu)', price:  175.00 , unit: '₺/kg', changePct: 2.1 },
   { name: 'Kestane', price: 211.90 , unit: '₺/kg', changePct: 0.2 },
   { name: 'Lavanta (Kuru Çiçek)', price: 110.00 , unit: '₺/kg', changePct: -2.5 },
   { name: 'Nane (Kuru)', price: 115.00  , unit: '₺/kg', changePct: 4.2 },
   { name: 'Kimyon', price: 195.00 , unit: '₺/kg', changePct: 1.5 },
   { name: 'Anason', price: 164 , unit: '₺/kg', changePct: 0.8 },
   { name: 'Rezene', price: 100 , unit: '₺/kg', changePct: 1.2 },
   { name: 'Biberiye', price: 95 , unit: '₺/kg', changePct: 2.3 },
   { name: 'Kuru Üzüm', price: 87.26, unit: '₺/kg', changePct: 0.44 },
   { name: 'Salçalık Domates', price: 3.45, unit: '₺/kg', changePct: 0.32 },
   { name: 'Yumurta', price: 3.05, unit: '₺/kg', changePct: 0.20 },
   { name: 'Bal', price: 247.26, unit: '₺/kg', changePct: 0.19 },
   { name: 'Yonca', price: 11.10, unit: '₺/kg', changePct: 0.97 },
   { name: 'Kuru Yaprak Kekik', price: 259.76, unit: '₺/kg', changePct: 1.11 },
   { name: 'Çörek Otu', price: 215.40, unit: '₺/kg', changePct: 3.4 },
   { name: 'Kuzu Göbeği Mantarı', price: 5172.68, unit: '₺/kg', changePct: 6.15 },
   { name: 'Kültür Mantarı', price: 109.35, unit: '₺/kg', changePct: 0.80 },
   { name: ' İstiridye Mantarı', price: 165, unit: '₺/kg', changePct: 0.73 }, 
   { name: 'Trüf Mantarı', price: 1800, unit: '₺/kg', changePct: 0.45 },
   { name: 'Çeltik', price: 36.94, unit: '₺/kg', changePct: 0.49 },
   { name: 'Soya Fasülyesi', price: 16.40, unit: '₺/kg', changePct: 0.90 },
  { name: 'Salatalık', price: 19.97, unit: '₺/kg', changePct: 0.60 },
  { name: 'Karpuz', price: 10.35, unit: '₺/kg', changePct: -0.20 },
  { name: 'Kavun', price: 21.20, unit: '₺/kg', changePct: 0.40 },
  { name: 'Kırmızı Mercimek', price: 42.0, unit: '₺/kg', changePct: 3.12 },
  { name: 'Canlı Hayvan', price: 411.19, unit: '₺/kg', changePct: -0.42 },
  { name: 'Antep Fıstığı', price: 580, unit: '₺/kg', changePct: 1.97 },
  { name: 'Marul', price: 41.12, unit: '₺/kg', changePct: 2.12 },
  { name: 'Zeytinyağı', price: 320, unit: '₺/lt', changePct: 0.34 },
];

// ── Tarımsal Endeksler ────────────────────────────────────────
export const indexMetrics: IndexMetric[] = [
  {
    id: 'girdi-maliyet',
    name: 'Girdi Maliyetleri Endeksi',
    value: 1842.6,
    unit: 'puan',
    changePct: 2.8,
    sparkline: makeSeries(11, 24, 1700, 18),
    description: 'Ülke geneli tarımsal girdi maliyetleri bileşik endeksi',
  },
  {
    id: 'gubre',
    name: 'Gübre Fiyat Endeksi',
    value: 2234.1,
    unit: 'puan',
    changePct: 4.2,
    sparkline: makeSeries(22, 24, 2050, 24),
    description: 'Azotlu, fosfatlı ve kompoze gübre fiyat eğilimi',
  },
  {
    id: 'mazot',
    name: 'Mazot Fiyat Endeksi',
    value: 1641.3,
    unit: 'puan',
    changePct: -1.6,
    sparkline: makeSeries(33, 24, 1680, 20),
    description: 'Tarımsal amaçlı motorin fiyat değişimi',
  },
  {
    id: 'tohum',
    name: 'Tohum Maliyet Endeksi',
    value: 1298.8,
    unit: 'puan',
    changePct: 1.1,
    sparkline: makeSeries(44, 24, 1230, 14),
    description: 'Sertifikalı tohum satış fiyat endeksi',
  },
  {
    id: 'elektrik',
    name: 'Sulama Elektrik Endeksi',
    value: 1512.0,
    unit: 'puan',
    changePct: 0.7,
    sparkline: makeSeries(55, 24, 1450, 12),
    description: 'Tarımsal sulama amaçlı elektrik tarifesi',
  },
  {
    id: 'iscilik',
    name: 'Tarım İşçiliği Endeksi',
    value: 1398.4,
    unit: 'puan',
    changePct: 2.1,
    sparkline: makeSeries(66, 24, 1300, 16),
    description: 'TÜİK Tarımsal İşletme İşgücü Ücret Yapısı: Mevsimlik 1.299 ₺/gün, Sürekli 37.305 ₺/ay',
  },
];

// ── Girdi Maliyet Zaman Serisi (12 ay) ────────────────────────
export const inputCostSeries: InputCostPoint[] = (() => {
  const months = ['Oca', 'Şub', 'Mar', 'Nis', 'May', 'Haz', 'Tem', 'Ağu', 'Eyl', 'Eki', 'Kas', 'Ara'];
  const g = makeSeries(71, 12, 100, 6);
  const m = makeSeries(72, 12, 100, 8);
  const t = makeSeries(73, 12, 100, 4);
  const i = makeSeries(74, 12, 100, 5);
  const e = makeSeries(75, 12, 100, 5);
  return months.map((month, idx) => ({
    month,
    gubre: 180 + g[idx] * 1.4,
    mazot: 160 + m[idx] * 1.2,
    tohum: 95 + t[idx] * 0.9,
    iscilik: 110 + i[idx] * 1.0,
    elektrik: 85 + e[idx] * 0.8,
  }));
})();

// ── Borsa Piyasaları ──────────────────────────────────────────
export const exchangeMarkets: ExchangeMarket[] = [
  {
    name: 'Konya Ticaret Borsası',
    city: 'Konya',
    totalVolume: 4_280_000,
    quotes: [
      { symbol: 'BUGD-K', exchange: 'Konya', city: 'Konya', product: 'Buğday (TSW)', last: 11.45, changePct: 1.32, volume: 1_240_000, unit: '₺/kg' },
      { symbol: 'CVDR-K', exchange: 'Konya', city: 'Konya', product: 'Çavdar (CDR)', last: 12.45, changePct: 1.12, volume: 1_240_000, unit: '₺/kg' },
      { symbol: 'ARPA-K', exchange: 'Konya', city: 'Konya', product: 'Arpa', last: 8.9, changePct: -0.78, volume: 980_000, unit: '₺/kg' },
      { symbol: 'MISIR-K', exchange: 'Konya', city: 'Konya', product: 'Mısır', last: 7.85, changePct: 0.56, volume: 760_000, unit: '₺/kg' },
      { symbol: 'AYCI-K', exchange: 'Konya', city: 'Konya', product: 'Ayçiçeği', last: 34.2, changePct: -1.14, volume: 1_300_000, unit: '₺/kg' },
    ],
  },
  {
    name: 'Polatlı Ticaret Borsası',
    city: 'Ankara',
    totalVolume: 2_140_000,
    quotes: [
      { symbol: 'BUGD-P', exchange: 'Polatlı', city: 'Ankara', product: 'Buğday (HD)', last: 11.2, changePct: 0.98, volume: 890_000, unit: '₺/kg' },
      { symbol: 'ARPA-P', exchange: 'Polatlı', city: 'Ankara', product: 'Arpa', last: 8.75, changePct: -0.52, volume: 620_000, unit: '₺/kg' },
      { symbol: 'NOC-P', exchange: 'Polatlı', city: 'Ankara', product: 'Nohut', last: 38.4, changePct: 1.74, volume: 340_000, unit: '₺/kg' },
      { symbol: 'MISIR-P', exchange: 'Polatlı', city: 'Ankara', product: 'Mısır', last: 7.7, changePct: 0.41, volume: 290_000, unit: '₺/kg' },
    ],
  },
  {
    name: 'İzmir Ticaret Borsası',
    city: 'İzmir',
    totalVolume: 3_610_000,
    quotes: [
      { symbol: 'PAMUK-I', exchange: 'İzmir', city: 'İzmir', product: 'Pamuk (Std 1)', last: 92.5, changePct: 2.41, volume: 1_100_000, unit: '₺/kg' },
      { symbol: 'ZEYT-I', exchange: 'İzmir', city: 'İzmir', product: 'Zeytinyağı', last: 240.0, changePct: 0.34, volume: 980_000, unit: '₺/lt' },
      { symbol: 'SUT-I', exchange: 'İzmir', city: 'İzmir', product: 'Süt (çiğ)', last: 18.65, changePct: 0.88, volume: 840_000, unit: '₺/lt' },
      { symbol: 'AYCI-I', exchange: 'İzmir', city: 'İzmir', product: 'Ayçiçeği', last: 34.8, changePct: -0.92, volume: 690_000, unit: '₺/kg' },
    ],
  },
  {
    name: 'Şanlıurfa Ticaret Borsası',
    city: 'Şanlıurfa',
    totalVolume: 5_120_000,
    quotes: [
      { symbol: 'PAMUK-U', exchange: 'Şanlıurfa', city: 'Şanlıurfa', product: 'Pamuk (Std 1)', last: 93.2, changePct: 2.78, volume: 2_400_000, unit: '₺/kg' },
      { symbol: 'MERC-U', exchange: 'Şanlıurfa', city: 'Şanlıurfa', product: 'Kırmızı Mercimek', last: 42.5, changePct: 3.42, volume: 1_100_000, unit: '₺/kg' },
      { symbol: 'BUGD-U', exchange: 'Şanlıurfa', city: 'Şanlıurfa', product: 'Buğday (HD)', last: 11.6, changePct: 1.54, volume: 980_000, unit: '₺/kg' },
      { symbol: 'ANTP-U', exchange: 'Şanlıurfa', city: 'Şanlıurfa', product: 'Antep Fıstığı', last: 585, changePct: 2.12, volume: 640_000, unit: '₺/kg' },
    ],
  },
  {
    name: 'Adana Ticaret Borsası',
    city: 'Adana',
    totalVolume: 3_850_000,
    quotes: [
      { symbol: 'PAMUK-A', exchange: 'Adana', city: 'Adana', product: 'Pamuk (Std 1)', last: 91.8, changePct: 2.15, volume: 1_500_000, unit: '₺/kg' },
      { symbol: 'MISIR-A', exchange: 'Adana', city: 'Adana', product: 'Mısır', last: 7.92, changePct: 0.72, volume: 920_000, unit: '₺/kg' },
      { symbol: 'SOYA-A', exchange: 'Adana', city: 'Adana', product: 'Soya Fasulyesi', last: 16.4, changePct: 0.9, volume: 580_000, unit: '₺/kg' },
      { symbol: 'AYCI-A', exchange: 'Adana', city: 'Adana', product: 'Ayçiçeği', last: 34.5, changePct: -0.8, volume: 850_000, unit: '₺/kg' },
    ],
  },
  {
    name: 'Gaziantep Ticaret Borsası',
    city: 'Gaziantep',
    totalVolume: 4_200_000,
    quotes: [
      { symbol: 'ANTP-G', exchange: 'Gaziantep', city: 'Gaziantep', product: 'Antep Fıstığı', last: 590, changePct: 2.35, volume: 1_800_000, unit: '₺/kg' },
      { symbol: 'BUGD-G', exchange: 'Gaziantep', city: 'Gaziantep', product: 'Buğday (HD)', last: 11.55, changePct: 1.42, volume: 1_200_000, unit: '₺/kg' },
      { symbol: 'MERC-G', exchange: 'Gaziantep', city: 'Gaziantep', product: 'Kırmızı Mercimek', last: 42.8, changePct: 3.15, volume: 700_000, unit: '₺/kg' },
      { symbol: 'NOC-G', exchange: 'Gaziantep', city: 'Gaziantep', product: 'Nohut', last: 39.2, changePct: 1.6, volume: 500_000, unit: '₺/kg' },
    ],
  },
  {
    name: 'Mersin Ticaret Borsası',
    city: 'Mersin',
    totalVolume: 2_980_000,
    quotes: [
      { symbol: 'SITRUS-M', exchange: 'Mersin', city: 'Mersin', product: 'Portakal', last: 34.45, changePct: 14.2, volume: 1_100_000, unit: '₺/kg' },
      { symbol: 'LIMON-M', exchange: 'Mersin', city: 'Mersin', product: 'Limon', last: 44.3, changePct: -6.7, volume: 880_000, unit: '₺/kg' },
      { symbol: 'DOMATES-M', exchange: 'Mersin', city: 'Mersin', product: 'Domates', last: 33.23, changePct: 0.63, volume: 600_000, unit: '₺/kg' },
      { symbol: 'MISIR-M', exchange: 'Mersin', city: 'Mersin', product: 'Mısır', last: 7.78, changePct: 0.48, volume: 400_000, unit: '₺/kg' },
    ],
  },
  {
    name: 'Antalya Ticaret Borsası',
    city: 'Antalya',
    totalVolume: 2_650_000,
    quotes: [
      { symbol: 'DOMATES-AN', exchange: 'Antalya', city: 'Antalya', product: 'Domates', last: 33.5, changePct: 0.8, volume: 980_000, unit: '₺/kg' },
      { symbol: 'BIBER-AN', exchange: 'Antalya', city: 'Antalya', product: 'Sivri Biber', last: 34.45, changePct: 4.8, volume: 720_000, unit: '₺/kg' },
      { symbol: 'PATATES-AN', exchange: 'Antalya', city: 'Antalya', product: 'Patates', last: 29.3, changePct: -2.2, volume: 550_000, unit: '₺/kg' },
      { symbol: 'NAR-AN', exchange: 'Antalya', city: 'Antalya', product: 'Nar', last: 65.0, changePct: 1.8, volume: 400_000, unit: '₺/kg' },
    ],
  },
  {
    name: 'Bursa Ticaret Borsası',
    city: 'Bursa',
    totalVolume: 3_120_000,
    quotes: [
      { symbol: 'KARPUZ-B', exchange: 'Bursa', city: 'Bursa', product: 'Karpuz', last: 10.35, changePct: -0.2, volume: 1_100_000, unit: '₺/kg' },
      { symbol: 'KAVUN-B', exchange: 'Bursa', city: 'Bursa', product: 'Kavun', last: 21.2, changePct: 0.4, volume: 800_000, unit: '₺/kg' },
      { symbol: 'SEFTALI-B', exchange: 'Bursa', city: 'Bursa', product: 'Şeftali', last: 54.0, changePct: 3.2, volume: 620_000, unit: '₺/kg' },
      { symbol: 'KIRAZ-B', exchange: 'Bursa', city: 'Bursa', product: 'Kiraz', last: 90.0, changePct: 8.3, volume: 600_000, unit: '₺/kg' },
    ],
  },
  {
    name: 'Tekirdağ (Trakya) Ticaret Borsası',
    city: 'Tekirdağ',
    totalVolume: 2_840_000,
    quotes: [
      { symbol: 'AYCI-T', exchange: 'Tekirdağ', city: 'Tekirdağ', product: 'Ayçiçeği', last: 34.6, changePct: -1.0, volume: 1_400_000, unit: '₺/kg' },
      { symbol: 'BUGD-T', exchange: 'Tekirdağ', city: 'Tekirdağ', product: 'Buğday (HD)', last: 11.3, changePct: 1.05, volume: 840_000, unit: '₺/kg' },
      { symbol: 'ARPA-T', exchange: 'Tekirdağ', city: 'Tekirdağ', product: 'Arpa', last: 8.82, changePct: -0.6, volume: 600_000, unit: '₺/kg' },
    ],
  },
  {
    name: 'Samsun Ticaret Borsası',
    city: 'Samsun',
    totalVolume: 1_980_000,
    quotes: [
      { symbol: 'FINDIK-S', exchange: 'Samsun', city: 'Samsun', product: 'Fındık (Kabuklu)', last: 140.0, changePct: 3.8, volume: 1_200_000, unit: '₺/kg' },
      { symbol: 'BUGD-S', exchange: 'Samsun', city: 'Samsun', product: 'Buğday', last: 11.4, changePct: 1.2, volume: 480_000, unit: '₺/kg' },
      { symbol: 'MISIR-S', exchange: 'Samsun', city: 'Samsun', product: 'Mısır', last: 7.8, changePct: 0.5, volume: 300_000, unit: '₺/kg' },
    ],
  },
  {
    name: 'Konya SE (Ticaret Borsası) — Yağlı Tohum',
    city: 'Konya',
    totalVolume: 1_750_000,
    quotes: [
      { symbol: 'AYCI-SE', exchange: 'Konya SE', city: 'Konya', product: 'Ayçiçeği', last: 34.2, changePct: -1.14, volume: 900_000, unit: '₺/kg' },
      { symbol: 'SOYA-SE', exchange: 'Konya SE', city: 'Konya', product: 'Soya Fasulyesi', last: 16.4, changePct: 0.9, volume: 500_000, unit: '₺/kg' },
      { symbol: 'KANOLA-SE', exchange: 'Konya SE', city: 'Konya', product: 'Kanola', last: 28.5, changePct: 1.1, volume: 350_000, unit: '₺/kg' },
    ],
  },
  {
    name: 'Diyarbakır Ticaret Borsası',
    city: 'Diyarbakır',
    totalVolume: 2_240_000,
    quotes: [
      { symbol: 'PAMUK-D', exchange: 'Diyarbakır', city: 'Diyarbakır', product: 'Pamuk (Std 1)', last: 92.8, changePct: 2.5, volume: 1_100_000, unit: '₺/kg' },
      { symbol: 'BUGD-D', exchange: 'Diyarbakır', city: 'Diyarbakır', product: 'Buğday (HD)', last: 11.5, changePct: 1.35, volume: 640_000, unit: '₺/kg' },
      { symbol: 'MERC-D', exchange: 'Diyarbakır', city: 'Diyarbakır', product: 'Kırmızı Mercimek', last: 42.3, changePct: 3.05, volume: 500_000, unit: '₺/kg' },
    ],
  },
  {
    name: 'Kayseri Ticaret Borsası',
    city: 'Kayseri',
    totalVolume: 1_860_000,
    quotes: [
      { symbol: 'BUGD-KY', exchange: 'Kayseri', city: 'Kayseri', product: 'Buğday', last: 11.38, changePct: 1.18, volume: 720_000, unit: '₺/kg' },
      { symbol: 'ARPA-KY', exchange: 'Kayseri', city: 'Kayseri', product: 'Arpa', last: 8.85, changePct: -0.65, volume: 540_000, unit: '₺/kg' },
      { symbol: 'MISIR-KY', exchange: 'Kayseri', city: 'Kayseri', product: 'Mısır', last: 7.82, changePct: 0.52, volume: 600_000, unit: '₺/kg' },
    ],
  },
  {
    name: 'Edirne Ticaret Borsası',
    city: 'Edirne',
    totalVolume: 1_520_000,
    quotes: [
      { symbol: 'AYCI-E', exchange: 'Edirne', city: 'Edirne', product: 'Ayçiçeği', last: 34.4, changePct: -0.95, volume: 880_000, unit: '₺/kg' },
      { symbol: 'BUGD-E', exchange: 'Edirne', city: 'Edirne', product: 'Buğday (HD)', last: 11.25, changePct: 0.98, volume: 420_000, unit: '₺/kg' },
      { symbol: 'ARPA-E', exchange: 'Edirne', city: 'Edirne', product: 'Arpa', last: 8.78, changePct: -0.55, volume: 220_000, unit: '₺/kg' },
    ],
  },
];

// Borsa ürün adından commodity ID'sine eşleştirme
export function matchCommodityId(productName: string): string | null {
  const lower = productName.toLowerCase();
  const found = commodities.find((c) => {
    const cName = c.name.toLowerCase();
    return lower.includes(cName) || cName.includes(lower);
  });
  return found ? found.id : null;
}

// ── Emtia / Ürün Analiz Modülü ────────────────────────────────
export const commodities: Commodity[] = [
  {
    id: 'bugday',
    name: 'Buğday',
    category: 'Hububat',
    icon: 'Wheat',
    unit: '₺/kg',
    price: 11.45,
    changeDay: 1.32,
    changeWeek: 2.84,
    changeMonth: 5.6,
    changeYear: 18.4,
    history: makeSeries(101, 30, 10.4, 0.6),
    priceHistory: makeDatedSeries(101, 120, 9.8, 0.7),
    costBreakdown: [
      { label: 'Gübre', amount: 1450, sharePct: 28 },
      { label: 'Tohum', amount: 680, sharePct: 13 },
      { label: 'İşçilik', amount: 1180, sharePct: 23 },
      { label: 'Sulama', amount: 520, sharePct: 10 },
      { label: 'Mazot/Makine', amount: 760, sharePct: 15 },
      { label: 'İlaçlama', amount: 480, sharePct: 11 },
    ],
    yieldPerDekar: 550,
    yieldUnit: 'kg',
    profitabilityRatio: 1.38,
    efficiencyScore: 78,
    region: 'İç Anadolu',
    harvestMonths: 'Haz — Tem',
  },
 
  {
    id: 'misir',
    name: 'Mısır',
    category: 'Hububat',
    icon: 'Corn',
    unit: '₺/kg',
    price: 7.85,
    changeDay: 0.56,
    changeWeek: 1.2,
    changeMonth: 3.1,
    changeYear: 14.2,
    history: makeSeries(102, 30, 7.2, 0.4),
    priceHistory: makeDatedSeries(102, 120, 6.9, 0.5),
    costBreakdown: [
      { label: 'Gübre', amount: 1620, sharePct: 30 },
      { label: 'Tohum', amount: 920, sharePct: 17 },
      { label: 'İşçilik', amount: 780, sharePct: 14 },
      { label: 'Sulama', amount: 1240, sharePct: 23 },
      { label: 'Mazot/Makine', amount: 560, sharePct: 10 },
      { label: 'İlaçlama', amount: 320, sharePct: 6 },
    ],
    yieldPerDekar: 1100,
    yieldUnit: 'kg',
    profitabilityRatio: 1.46,
    efficiencyScore: 82,
    region: 'Akdeniz / Ege',
    harvestMonths: 'Eyl — Eki',
  },
 {
    id: 'yulaf-ezmesi',
    name: 'Yulaf Ezmesi',
    category: 'Hububat Mamulleri',
    icon: 'Wheat',
    unit: '₺/kg',
    price: 48.0,
    changeDay: 0.4,
    changeWeek: 1.2,
    changeMonth: 3.8,
    changeYear: 22.4,
    history: makeSeries(212, 30, 42, 0.6),
    priceHistory: makeDatedSeries(212, 120, 38, 1.2),
    costBreakdown: [
      { label: 'Ham Yulaf (Hammadde)', amount: 18500, sharePct: 52 },
      { label: 'Buharlama & Vals Enerjisi', amount: 5700, sharePct: 16 },
      { label: 'Paketleme & Kilitli Torba', amount: 4600, sharePct: 13 },
      { label: 'İşçilik', amount: 3550, sharePct: 10 },
      { label: 'Bakım/Amortisman', amount: 2150, sharePct: 6 },
      { label: 'Diğer', amount: 1100, sharePct: 3 },
    ],
    yieldPerDekar: 0,
    yieldUnit: 'kg',
    profitabilityRatio: 1.35,
    efficiencyScore: 82,
    region: 'İç Anadolu / Ege',
    harvestMonths: 'Yıl boyu',
  },
  {
    id: 'misir-gevregi',
    name: 'Mısır Gevreği',
    category: 'Hububat Mamulleri',
    icon: 'Utensils',
    unit: '₺/kg',
    price: 65.0,
    changeDay: -0.2,
    changeWeek: 0.8,
    changeMonth: 2.1,
    changeYear: 18.5,
    history: makeSeries(213, 30, 58, 0.5),
    priceHistory: makeDatedSeries(213, 120, 52, 1.1),
    costBreakdown: [
      { label: 'Mısır İrmiği (Hammadde)', amount: 16000, sharePct: 40 },
      { label: 'Pişirme & Fırınlama Enerjisi', amount: 8000, sharePct: 20 },
      { label: 'Kutu & İç Folyo Paketleme', amount: 5600, sharePct: 14 },
      { label: 'Katkı/Tatlandırıcı/Vitamin', amount: 4800, sharePct: 12 },
      { label: 'İşçilik', amount: 3600, sharePct: 9 },
      { label: 'Bakım/Amortisman', amount: 2000, sharePct: 5 },
    ],
    yieldPerDekar: 0,
    yieldUnit: 'kg',
    profitabilityRatio: 1.42,
    efficiencyScore: 78,
    region: 'Akdeniz / Marmara',
    harvestMonths: 'Yıl boyu',
  },
  {
    id: 'tarhana',
    name: 'Tarhana',
    category: 'Hububat Mamulleri',
    icon: 'Soup',
    unit: '₺/kg',
    price: 110.0,
    changeDay: 0.1,
    changeWeek: 0.5,
    changeMonth: 5.2,
    changeYear: 28.0,
    history: makeSeries(214, 30, 95, 0.4),
    priceHistory: makeDatedSeries(214, 120, 85, 1.5),
    costBreakdown: [
      { label: 'Yoğurt, Sebze ve Un', amount: 34000, sharePct: 48 },
      { label: 'Yoğurma ve Fermantasyon İşçiliği', amount: 15600, sharePct: 22 },
      { label: 'Kurutma Enerjisi/Alanı', amount: 9900, sharePct: 14 },
      { label: 'Baharat & Doğal Katkılar', amount: 5000, sharePct: 7 },
      { label: 'Paketleme (Kavanoz/Kese)', amount: 4200, sharePct: 6 },
      { label: 'Diğer', amount: 2100, sharePct: 3 },
    ],
    yieldPerDekar: 0,
    yieldUnit: 'kg',
    profitabilityRatio: 1.55,
    efficiencyScore: 70,
    region: 'Ege / İç Anadolu',
    harvestMonths: 'Ağu — Eki',
  },
  {
    id: 'kuskus',
    name: 'Kuskus',
    category: 'Hububat Mamulleri',
    icon: 'CircleDot',
    unit: '₺/kg',
    price: 36.0,
    changeDay: 0.3,
    changeWeek: 1.1,
    changeMonth: 3.2,
    changeYear: 19.4,
    history: makeSeries(215, 30, 31, 0.7),
    priceHistory: makeDatedSeries(215, 120, 28, 0.9),
    costBreakdown: [
      { label: 'Durum Buğdayı / İrmik', amount: 15400, sharePct: 55 },
      { label: 'Buhar ve Kurutma Enerjisi', amount: 4500, sharePct: 16 },
      { label: 'İşçilik', amount: 3100, sharePct: 11 },
      { label: 'Paketleme', amount: 2500, sharePct: 9 },
      { label: 'Bakım/Amortisman', amount: 1700, sharePct: 6 },
      { label: 'Diğer', amount: 800, sharePct: 3 },
    ],
    yieldPerDekar: 0,
    yieldUnit: 'kg',
    profitabilityRatio: 1.28,
    efficiencyScore: 80,
    region: 'Güneydoğu / İç Anadolu',
    harvestMonths: 'Yıl boyu',
  },
  {
    id: 'bulgur',
    name: 'Bulgur',
    category: 'Hububat Mamulleri',
    icon: 'Wheat',
    unit: '₺/kg',
    price: 28.0,
    changeDay: 0.5,
    changeWeek: 1.4,
    changeMonth: 2.8,
    changeYear: 17.5,
    history: makeSeries(216, 30, 25, 0.6),
    priceHistory: makeDatedSeries(216, 120, 23, 0.8),
    costBreakdown: [
      { label: 'Sert Buğday (Hammadde)', amount: 15600, sharePct: 60 },
      { label: 'Haşlama & Kurutma Enerjisi', amount: 3900, sharePct: 15 },
      { label: 'Kırma ve Eleme İşçiliği', amount: 2600, sharePct: 10 },
      { label: 'Bakım/Amortisman', amount: 1800, sharePct: 7 },
      { label: 'Paketleme', amount: 1300, sharePct: 5 },
      { label: 'Diğer', amount: 800, sharePct: 3 },
    ],
    yieldPerDekar: 0,
    yieldUnit: 'kg',
    profitabilityRatio: 1.22,
    efficiencyScore: 85,
    region: 'Güneydoğu Anadolu',
    harvestMonths: 'Yıl boyu',
  },
  {
    id: 'irmik',
    name: 'İrmik',
    category: 'Hububat Mamulleri',
    icon: 'Sparkles',
    unit: '₺/kg',
    price: 26.5,
    changeDay: 0.2,
    changeWeek: 0.9,
    changeMonth: 3.1,
    changeYear: 15.8,
    history: makeSeries(217, 30, 23, 0.5),
    priceHistory: makeDatedSeries(217, 120, 21.5, 0.7),
    costBreakdown: [
      { label: 'Durum Buğdayı (Hammadde)', amount: 16100, sharePct: 67 },
      { label: 'Öğütme & Eleme Enerjisi', amount: 3100, sharePct: 13 },
      { label: 'İşçilik', amount: 2150, sharePct: 9 },
      { label: 'Bakım/Amortisman', amount: 1450, sharePct: 6 },
      { label: 'Paketleme', amount: 800, sharePct: 3 },
      { label: 'Diğer', amount: 400, sharePct: 2 },
    ],
    yieldPerDekar: 0,
    yieldUnit: 'kg',
    profitabilityRatio: 1.2,
    efficiencyScore: 88,
    region: 'Güneydoğu / İç Anadolu',
    harvestMonths: 'Yıl boyu',
  },
  {
    id: 'domates',
    name: 'Domates',
    category: 'Sebzeler',
    icon: 'Tomatoes',
    unit: '₺/kg',
    price: 33.23,
    changeDay: 0.63,
    changeWeek: 2.2,
    changeMonth: 5.1,
    changeYear: 30.27,
    history: makeSeries(120, 45, 9.7, 2.4),
    priceHistory: makeDatedSeries(130, 150, 11.8, 3.5),
    costBreakdown: [
      { label: 'Gübre', amount: 9000, sharePct: 16.4 },
      { label: 'Tohum', amount: 8000, sharePct: 14.5 },
      { label: 'İşçilik', amount: 1100, sharePct: 20 },
      { label: 'Sulama', amount: 5000, sharePct: 9.1 },
      { label: 'Mazot/Makine', amount: 7000, sharePct: 12.7 },
      { label: 'İlaçlama', amount: 7000, sharePct: 12.7 },
    ],
    yieldPerDekar: 1100,
    yieldUnit: 'kg',
    profitabilityRatio: 1.5,
    efficiencyScore: 93,
    region: 'Akdeniz / Ege',
    harvestMonths: 'Tem — Eki',
  },
  {
    id: 'sut',
    name: 'Süt (çiğ)',
    category: 'Süt ve Süt Ürünleri',
    icon: 'Milk',
    unit: '₺/lt',
    price: 18.65,
    changeDay: 0.88,
    changeWeek: 1.4,
    changeMonth: 2.2,
    changeYear: 9.8,
    history: makeSeries(103, 30, 17.8, 0.35),
    priceHistory: makeDatedSeries(103, 120, 17.4, 0.4),
    costBreakdown: [
      { label: 'Yem', amount: 9800, sharePct: 52 },
      { label: 'İşçilik', amount: 3200, sharePct: 17 },
      { label: 'Sağlık/Bakım', amount: 1400, sharePct: 7 },
      { label: 'Elektrik', amount: 1100, sharePct: 6 },
      { label: 'Su', amount: 480, sharePct: 3 },
      { label: 'Diğer', amount: 2820, sharePct: 15 },
    ],
    yieldPerDekar: 0,
    yieldUnit: 'lt/inek/gün',
    profitabilityRatio: 1.12,
    efficiencyScore: 68,
    region: 'Marmara / Ege',
    harvestMonths: 'Yıl boyu',
  },
  {
    id: 'pamuk',
    name: 'Pamuk',
    category: 'Endüstriyel',
    icon: 'Cotton',
    unit: '₺/kg',
    price: 92.5,
    changeDay: 2.41,
    changeWeek: 4.1,
    changeMonth: 7.8,
    changeYear: 22.5,
    history: makeSeries(104, 30, 84, 3),
    priceHistory: makeDatedSeries(104, 120, 80, 3.5),
    costBreakdown: [
      { label: 'Gübre', amount: 2100, sharePct: 26 },
      { label: 'Tohum', amount: 740, sharePct: 9 },
      { label: 'İşçilik', amount: 2400, sharePct: 30 },
      { label: 'Sulama', amount: 1180, sharePct: 15 },
      { label: 'Mazot/Makine', amount: 980, sharePct: 12 },
      { label: 'İlaçlama', amount: 620, sharePct: 8 },
    ],
    yieldPerDekar: 480,
    yieldUnit: 'kg',
    profitabilityRatio: 1.52,
    efficiencyScore: 74,
    region: 'Güneydoğu Anadolu',
    harvestMonths: 'Eyl — Kas',
  },
  {
    id: 'aycicegi',
    name: 'Ayçiçeği',
    category: 'Yağlı Tohum',
    icon: 'Sun',
    unit: '₺/kg',
    price: 34.2,
    changeDay: -1.14,
    changeWeek: -2.1,
    changeMonth: 1.4,
    changeYear: 11.6,
    history: makeSeries(105, 30, 33.4, 1.1),
    priceHistory: makeDatedSeries(105, 120, 32.5, 1.3),
    costBreakdown: [
      { label: 'Gübre', amount: 1480, sharePct: 27 },
      { label: 'Tohum', amount: 620, sharePct: 11 },
      { label: 'İşçilik', amount: 1240, sharePct: 23 },
      { label: 'Sulama', amount: 720, sharePct: 13 },
      { label: 'Mazot/Makine', amount: 820, sharePct: 15 },
      { label: 'İlaçlama', amount: 580, sharePct: 11 },
    ],
    yieldPerDekar: 280,
    yieldUnit: 'kg',
    profitabilityRatio: 1.22,
    efficiencyScore: 64,
    region: 'Marmara / Trakya',
    harvestMonths: 'Eyl — Eki',
  },
  {
    id: 'canlihayvan',
    name: 'Canlı Hayvan (Büyükbaş)',
    category: 'Canlı Hayvanlar',
    icon: ' Beef',
    unit: '₺/kg',
    price: 320,
    changeDay: -0.42,
    changeWeek: 0.8,
    changeMonth: 2.6,
    changeYear: 12.4,
    history: makeSeries(106, 30, 305, 8),
    priceHistory: makeDatedSeries(106, 120, 295, 9),
    costBreakdown: [
      { label: 'Yem', amount: 42000, sharePct: 58 },
      { label: 'İşçilik', amount: 9800, sharePct: 14 },
      { label: 'Sağlık/Bakım', amount: 5400, sharePct: 8 },
      { label: 'Barınak/Energy', amount: 6200, sharePct: 9 },
      { label: 'Su', amount: 1800, sharePct: 3 },
      { label: 'Diğer', amount: 6400, sharePct: 8 },
    ],
    yieldPerDekar: 0,
    yieldUnit: 'kg canlı ağırlık',
    profitabilityRatio: 1.18,
    efficiencyScore: 61,
    region: 'Doğu Anadolu',
    harvestMonths: 'Yıl boyu',
  },
  {
    id: 'mercimek',
    name: 'Kırmızı Mercimek',
    category: 'Bakliyat',
    icon: 'Dot',
    unit: '₺/kg',
    price: 42.0,
    changeDay: 3.12,
    changeWeek: 5.4,
    changeMonth: 8.2,
    changeYear: 19.1,
    history: makeSeries(107, 30, 38, 1.4),
    priceHistory: makeDatedSeries(107, 120, 36, 1.6),
    costBreakdown: [
      { label: 'Gübre', amount: 980, sharePct: 22 },
      { label: 'Tohum', amount: 1240, sharePct: 28 },
      { label: 'İşçilik', amount: 1080, sharePct: 24 },
      { label: 'Sulama', amount: 240, sharePct: 5 },
      { label: 'Mazot/Makine', amount: 620, sharePct: 14 },
      { label: 'İlaçlama', amount: 320, sharePct: 7 },
    ],
    yieldPerDekar: 220,
    yieldUnit: 'kg',
    profitabilityRatio: 1.41,
    efficiencyScore: 72,
    region: 'Güneydoğu Anadolu',
    harvestMonths: 'Haz — Tem',
  },
  {
    id: 'zeytinyagi',
    name: 'Zeytinyağı',
    category: 'Bitkisel Yağlar',
    icon: ' Droplet',
    unit: '₺/lt',
    price: 240.0,
    changeDay: 0.34,
    changeWeek: 1.1,
    changeMonth: 4.2,
    changeYear: 16.8,
    history: makeSeries(108, 30, 228, 5),
    priceHistory: makeDatedSeries(108, 120, 218, 6),
    costBreakdown: [
      { label: 'İşçilik (hasat)', amount: 4200, sharePct: 38 },
      { label: 'İşleme/Sıkım', amount: 2400, sharePct: 22 },
      { label: 'Gübre', amount: 980, sharePct: 9 },
      { label: 'Sulama', amount: 1200, sharePct: 11 },
      { label: 'Mazot/Makine', amount: 1480, sharePct: 13 },
      { label: 'İlaçlama', amount: 1180, sharePct: 7 },
    ],
    yieldPerDekar: 180,
    yieldUnit: 'lt',
    profitabilityRatio: 1.34,
    efficiencyScore: 70,
    region: 'Ege / Akdeniz',
    harvestMonths: 'Kas — Şub',
  },
  {
    id: 'arpa',
    name: 'Arpa',
    category: 'Hububat',
    icon: 'Wheat',
    unit: '₺/kg',
    price: 8.9,
    changeDay: -0.78,
    changeWeek: 0.42,
    changeMonth: 2.1,
    changeYear: 13.5,
    history: makeSeries(109, 30, 8.4, 0.4),
    priceHistory: makeDatedSeries(109, 120, 8.1, 0.45),
    costBreakdown: [
      { label: 'Gübre', amount: 1320, sharePct: 27 },
      { label: 'Tohum', amount: 580, sharePct: 12 },
      { label: 'İşçilik', amount: 1080, sharePct: 22 },
      { label: 'Sulama', amount: 460, sharePct: 9 },
      { label: 'Mazot/Makine', amount: 820, sharePct: 17 },
      { label: 'İlaçlama', amount: 440, sharePct: 9 },
    ],
    yieldPerDekar: 480,
    yieldUnit: 'kg',
    profitabilityRatio: 1.31,
    efficiencyScore: 75,
    region: 'İç Anadolu',
    harvestMonths: 'Haz — Tem',
  },
   {
    id: 'nohut',
    name: 'Nohut',
    category: 'Bakliyat',
    icon: 'Dot',
    unit: '₺/kg',
    price: 38.4,
    changeDay: 1.74,
    changeWeek: 3.2,
    changeMonth: 6.4,
    changeYear: 15.8,
    history: makeSeries(110, 30, 35.5, 1.2),
    priceHistory: makeDatedSeries(110, 120, 34, 1.4),
    costBreakdown: [
      { label: 'Gübre', amount: 1040, sharePct: 23 },
      { label: 'Tohum', amount: 1180, sharePct: 26 },
      { label: 'İşçilik', amount: 1120, sharePct: 25 },
      { label: 'Sulama', amount: 320, sharePct: 7 },
      { label: 'Mazot/Makine', amount: 580, sharePct: 13 },
      { label: 'İlaçlama', amount: 280, sharePct: 6 },
    ],
    yieldPerDekar: 200,
    yieldUnit: 'kg',
    profitabilityRatio: 1.35,
    efficiencyScore: 68,
    region: 'İç Anadolu / GAP',
    harvestMonths: 'Tem — Eyl',
  },
  {
    id: 'cavdar',
    name: 'Çavdar',
    category: 'Hububat',
    icon: 'Rye',
    unit: '₺/kg',
    price: 12.5,
    changeDay: 1.20,
    changeWeek: 3.2,
    changeMonth: 6.4,
    changeYear: 15.8,
    history: makeSeries(110, 30, 35.5, 1.2),
    priceHistory: makeDatedSeries(110, 120, 34, 1.4),
    costBreakdown: [
      { label: 'Gübre', amount: 1040, sharePct: 23 },
      { label: 'Tohum', amount: 1180, sharePct: 26 },
      { label: 'İşçilik', amount: 1120, sharePct: 25 },
      { label: 'Sulama', amount: 320, sharePct: 7 },
      { label: 'Mazot/Makine', amount: 580, sharePct: 13 },
      { label: 'İlaçlama', amount: 280, sharePct: 6 },
    ],
    yieldPerDekar: 200,
    yieldUnit: 'kg',
    profitabilityRatio: 1.35,
    efficiencyScore: 68,
    region: 'İç Anadolu / GAP',
    harvestMonths: 'Tem — Eyl',
  },
  {
    id: 'antepfistigi',
    name: 'Antep Fıstığı',
    category: 'Sert Kabuklular',
    icon: 'Dot',
    unit: '₺/kg',
    price: 585,
    changeDay: 2.12,
    changeWeek: 4.6,
    changeMonth: 8.8,
    changeYear: 24.2,
    history: makeSeries(111, 30, 545, 16),
    priceHistory: makeDatedSeries(111, 120, 520, 18),
    costBreakdown: [
      { label: 'İşçilik', amount: 8200, sharePct: 42 },
      { label: 'Gübre', amount: 2400, sharePct: 12 },
      { label: 'Sulama', amount: 2800, sharePct: 14 },
      { label: 'Mazot/Makine', amount: 3200, sharePct: 16 },
      { label: 'İlaçlama', amount: 1800, sharePct: 9 },
      { label: 'Tohum/Fidan', amount: 1400, sharePct: 7 },
    ],
    yieldPerDekar: 120,
    yieldUnit: 'kg',
    profitabilityRatio: 1.48,
    efficiencyScore: 66,
    region: 'GAP / Akdeniz',
    harvestMonths: 'Eyl — Eki',
  },
  {
    id: 'yumurta',
    name: 'Yumurta',
    category: 'Kümes Hayvancılığı',
    icon: 'Egg',
    unit: '₺/adet',
    price: 3.05,
    changeDay: 0.20,
    changeWeek: 1.1,
    changeMonth: 3.4,
    changeYear: 12.8,
    history: makeSeries(201, 30, 2.8, 0.15),
    priceHistory: makeDatedSeries(201, 120, 2.7, 0.18),
    costBreakdown: [
      { label: 'Yem', amount: 6800, sharePct: 62 },
      { label: 'İşçilik', amount: 1600, sharePct: 15 },
      { label: 'Sağlık/Aşı', amount: 900, sharePct: 8 },
      { label: 'Elektrik', amount: 700, sharePct: 6 },
      { label: 'Barınak', amount: 500, sharePct: 5 },
      { label: 'Diğer', amount: 400, sharePct: 4 },
    ],
    yieldPerDekar: 0,
    yieldUnit: 'adet/tavuk/gün',
    profitabilityRatio: 1.22,
    efficiencyScore: 72,
    region: 'Marmara / İç Anadolu',
    harvestMonths: 'Yıl boyu',
  },
  {
    id: 'bal',
    name: 'Bal',
    category: 'Arıcılık Ürünleri',
    icon: 'Hexagon',
    unit: '₺/kg',
    price: 247.26,
    changeDay: 0.19,
    changeWeek: 0.8,
    changeMonth: 2.1,
    changeYear: 8.4,
    history: makeSeries(202, 30, 230, 6),
    priceHistory: makeDatedSeries(202, 120, 225, 7),
    costBreakdown: [
      { label: 'Kovan/Bakım', amount: 3200, sharePct: 35 },
      { label: 'İşçilik', amount: 2800, sharePct: 30 },
      { label: 'Şeker/Şurup', amount: 1400, sharePct: 15 },
      { label: 'Nakliye', amount: 900, sharePct: 10 },
      { label: 'Sağlık', amount: 500, sharePct: 5 },
      { label: 'Diğer', amount: 500, sharePct: 5 },
    ],
    yieldPerDekar: 0,
    yieldUnit: 'kg/kovan',
    profitabilityRatio: 1.35,
    efficiencyScore: 70,
    region: 'Karadeniz / Akdeniz',
    harvestMonths: 'Nis — Eyl',
  },
  {
    id: 'yas-pek',
    name: 'Yaş İpek Kozası',
    category: 'İpek Böcekçiliği',
    icon: 'Spool',
    unit: '₺/kg',
    price: 1850,
    changeDay: 0.45,
    changeWeek: 1.2,
    changeMonth: 3.8,
    changeYear: 15.2,
    history: makeSeries(203, 30, 1700, 40),
    priceHistory: makeDatedSeries(203, 120, 1650, 45),
    costBreakdown: [
      { label: 'Dut Yaprağı', amount: 12000, sharePct: 48 },
      { label: 'İşçilik', amount: 8000, sharePct: 32 },
      { label: 'Kovan/Ekipman', amount: 3000, sharePct: 12 },
      { label: 'İşleme', amount: 1500, sharePct: 6 },
      { label: 'Diğer', amount: 500, sharePct: 2 },
    ],
    yieldPerDekar: 0,
    yieldUnit: 'kg',
    profitabilityRatio: 1.28,
    efficiencyScore: 58,
    region: 'Marmara / Akdeniz',
    harvestMonths: 'May — Eyl',
  },
  {
    id: 'hamsi',
    name: 'Hamsi',
    category: 'Deniz Balıkları',
    icon: 'Fish',
    unit: '₺/kg',
    price: 95.5,
    changeDay: 1.8,
    changeWeek: 3.2,
    changeMonth: 6.5,
    changeYear: 20.4,
    history: makeSeries(204, 30, 85, 4),
    priceHistory: makeDatedSeries(204, 120, 82, 5),
    costBreakdown: [
      { label: 'Yakıt/Mazot', amount: 28000, sharePct: 45 },
      { label: 'İşçilik', amount: 12000, sharePct: 19 },
      { label: 'Ağ/Ekipman', amount: 8000, sharePct: 13 },
      { label: 'Buz/Konso', amount: 6000, sharePct: 10 },
      { label: 'Bakım', amount: 5000, sharePct: 8 },
      { label: 'Diğer', amount: 3000, sharePct: 5 },
    ],
    yieldPerDekar: 0,
    yieldUnit: 'kg/tekne',
    profitabilityRatio: 1.32,
    efficiencyScore: 65,
    region: 'Karadeniz',
    harvestMonths: 'Eki — Nis',
  },
  {
    id: 'alabalik',
    name: 'Alabalık',
    category: 'İç Su Balıkları',
    icon: 'Fish',
    unit: '₺/kg',
    price: 180,
    changeDay: 0.6,
    changeWeek: 1.4,
    changeMonth: 4.2,
    changeYear: 14.8,
    history: makeSeries(205, 30, 165, 5),
    priceHistory: makeDatedSeries(205, 120, 160, 6),
    costBreakdown: [
      { label: 'Yem', amount: 95000, sharePct: 58 },
      { label: 'Su/Sirkülasyon', amount: 22000, sharePct: 13 },
      { label: 'İşçilik', amount: 20000, sharePct: 12 },
      { label: 'Yavru', amount: 15000, sharePct: 9 },
      { label: 'Elektrik', amount: 8000, sharePct: 5 },
      { label: 'Diğer', amount: 4000, sharePct: 3 },
    ],
    yieldPerDekar: 0,
    yieldUnit: 'kg',
    profitabilityRatio: 1.26,
    efficiencyScore: 68,
    region: 'İç Anadolu / Karadeniz',
    harvestMonths: 'Yıl boyu',
  },
  {
    id: 'karides',
    name: 'Karides',
    category: 'Kabuklu ve Yumuşakçalar',
    icon: 'Fish',
    unit: '₺/kg',
    price: 420,
    changeDay: 1.1,
    changeWeek: 2.5,
    changeMonth: 5.8,
    changeYear: 18.2,
    history: makeSeries(206, 30, 390, 12),
    priceHistory: makeDatedSeries(206, 120, 380, 14),
    costBreakdown: [
      { label: 'Yavru/Postlar', amount: 180000, sharePct: 40 },
      { label: 'Yem', amount: 120000, sharePct: 27 },
      { label: 'Su/Klorlama', amount: 60000, sharePct: 13 },
      { label: 'İşçilik', amount: 45000, sharePct: 10 },
      { label: 'Elektrik', amount: 25000, sharePct: 6 },
      { label: 'Diğer', amount: 15000, sharePct: 4 },
    ],
    yieldPerDekar: 0,
    yieldUnit: 'kg',
    profitabilityRatio: 1.30,
    efficiencyScore: 60,
    region: 'Ege / Akdeniz',
    harvestMonths: 'May — Eki',
  },
  {
    id: 'kereste',
    name: 'Kereste',
    category: 'Odunsu Orman Ürünleri',
    icon: 'TreePine',
    unit: '₺/m³',
    price: 3200,
    changeDay: 0.3,
    changeWeek: 0.9,
    changeMonth: 2.8,
    changeYear: 11.5,
    history: makeSeries(207, 30, 2950, 60),
    priceHistory: makeDatedSeries(207, 120, 2850, 70),
    costBreakdown: [
      { label: 'Kesim/İşçilik', amount: 45000, sharePct: 38 },
      { label: 'Nakliye', amount: 28000, sharePct: 24 },
      { label: 'Ekipman/Yakıt', amount: 20000, sharePct: 17 },
      { label: 'Bakım', amount: 12000, sharePct: 10 },
      { label: 'Ruhsat/İzin', amount: 8000, sharePct: 7 },
      { label: 'Diğer', amount: 5000, sharePct: 4 },
    ],
    yieldPerDekar: 0,
    yieldUnit: 'm³',
    profitabilityRatio: 1.20,
    efficiencyScore: 55,
    region: 'Karadeniz / Akdeniz',
    harvestMonths: 'Yıl boyu',
  },
  {
    id: 'cam-fistigi',
    name: 'Çam Fıstığı',
    category: 'Odun Dışı Orman Ürünleri',
    icon: 'TreePine',
    unit: '₺/kg',
    price: 680,
    changeDay: 1.5,
    changeWeek: 3.8,
    changeMonth: 7.2,
    changeYear: 22.1,
    history: makeSeries(208, 30, 620, 18),
    priceHistory: makeDatedSeries(208, 120, 600, 20),
    costBreakdown: [
      { label: 'İşçilik (Toplama)', amount: 42000, sharePct: 55 },
      { label: 'Nakliye', amount: 12000, sharePct: 16 },
      { label: 'Ekipman', amount: 8000, sharePct: 10 },
      { label: 'Kuru/İşleme', amount: 6000, sharePct: 8 },
      { label: 'Ruhsat', amount: 5000, sharePct: 7 },
      { label: 'Diğer', amount: 3000, sharePct: 4 },
    ],
    yieldPerDekar: 0,
    yieldUnit: 'kg',
    profitabilityRatio: 1.42,
    efficiencyScore: 62,
    region: 'Akdeniz / Ege',
    harvestMonths: 'Kas — Şub',
  },
  {
    id: 'yun',
    name: 'Yün',
    category: 'Lifler ve Yapağılar',
    icon: 'Spool',
    unit: '₺/kg',
    price: 85,
    changeDay: 0.4,
    changeWeek: 1.0,
    changeMonth: 2.5,
    changeYear: 9.8,
    history: makeSeries(209, 30, 78, 2.5),
    priceHistory: makeDatedSeries(209, 120, 75, 3),
    costBreakdown: [
      { label: 'Kırkım/İşçilik', amount: 18000, sharePct: 48 },
      { label: 'Yem/Bakım', amount: 10000, sharePct: 27 },
      { label: 'Sağlık', amount: 4000, sharePct: 11 },
      { label: 'Paketleme', amount: 3000, sharePct: 8 },
      { label: 'Nakliye', amount: 1500, sharePct: 4 },
      { label: 'Diğer', amount: 1000, sharePct: 2 },
    ],
    yieldPerDekar: 0,
    yieldUnit: 'kg/koyun',
    profitabilityRatio: 1.15,
    efficiencyScore: 56,
    region: 'İç Anadolu / Doğu Anadolu',
    harvestMonths: 'May — Haz',
  },
  {
    id: 'ham-deri',
    name: 'Ham Deri (Büyükbaş)',
    category: 'Ham Deriler',
    icon: 'Layers',
    unit: '₺/adet',
    price: 450,
    changeDay: 0.2,
    changeWeek: 0.7,
    changeMonth: 1.8,
    changeYear: 7.2,
    history: makeSeries(210, 30, 420, 8),
    priceHistory: makeDatedSeries(210, 120, 410, 10),
    costBreakdown: [
      { label: 'Kesimhane', amount: 12000, sharePct: 40 },
      { label: 'Tuzlama/Konservasyon', amount: 8000, sharePct: 27 },
      { label: 'İşçilik', amount: 5000, sharePct: 17 },
      { label: 'Nakliye', amount: 3000, sharePct: 10 },
      { label: 'Depolama', amount: 1500, sharePct: 5 },
      { label: 'Diğer', amount: 500, sharePct: 1 },
    ],
    yieldPerDekar: 0,
    yieldUnit: 'adet',
    profitabilityRatio: 1.10,
    efficiencyScore: 50,
    region: 'Tüm bölgeler',
    harvestMonths: 'Yıl boyu',
  },
  {
    id: 'un',
    name: 'Un',
    category: 'Hububat Mamulleri',
    icon: 'Wheat',
    unit: '₺/kg',
    price: 22.5,
    changeDay: 0.8,
    changeWeek: 1.9,
    changeMonth: 4.5,
    changeYear: 16.2,
    history: makeSeries(211, 30, 20, 0.8),
    priceHistory: makeDatedSeries(211, 120, 19, 1),
    costBreakdown: [
      { label: 'Buğday (Hammadde)', amount: 14000, sharePct: 65 },
      { label: 'Enerji/Elektrik', amount: 3000, sharePct: 14 },
      { label: 'İşçilik', amount: 2000, sharePct: 9 },
      { label: 'Bakım/Amortisman', amount: 1500, sharePct: 7 },
      { label: 'Paketleme', amount: 700, sharePct: 3 },
      { label: 'Diğer', amount: 300, sharePct: 2 },
    ],
    yieldPerDekar: 0,
    yieldUnit: 'kg',
    profitabilityRatio: 1.25,
    efficiencyScore: 75,
    region: 'İç Anadolu / Marmara',
    harvestMonths: 'Yıl boyu',
  },
  {
    id: 'aycicek-yagi',
    name: 'Ayçiçek Yağı',
    category: 'Bitkisel Yağlar',
    icon: 'Droplet',
    unit: '₺/lt',
    price: 78.5,
    changeDay: -0.5,
    changeWeek: -1.2,
    changeMonth: 2.0,
    changeYear: 10.8,
    history: makeSeries(212, 30, 75, 2),
    priceHistory: makeDatedSeries(212, 120, 73, 2.5),
    costBreakdown: [
      { label: 'Ayçiçeği (Hammadde)', amount: 38000, sharePct: 72 },
      { label: 'Enerji/İşleme', amount: 6000, sharePct: 11 },
      { label: 'İşçilik', amount: 3500, sharePct: 7 },
      { label: 'Paketleme', amount: 2500, sharePct: 5 },
      { label: 'Bakım', amount: 2000, sharePct: 4 },
      { label: 'Diğer', amount: 1000, sharePct: 1 },
    ],
    yieldPerDekar: 0,
    yieldUnit: 'lt',
    profitabilityRatio: 1.18,
    efficiencyScore: 72,
    region: 'Marmara / Trakya',
    harvestMonths: 'Eyl — Mar',
  },
  {
    id: 'ayci-kuspesi',
    name: 'Ayçiçek Küspesi',
    category: 'Küspeler ve Pirina',
    icon: 'Layers',
    unit: '₺/kg',
    price: 12.8,
    changeDay: 0.3,
    changeWeek: 0.9,
    changeMonth: 2.2,
    changeYear: 8.5,
    history: makeSeries(213, 30, 11.5, 0.4),
    priceHistory: makeDatedSeries(213, 120, 11, 0.5),
    costBreakdown: [
      { label: 'Hammadde', amount: 8000, sharePct: 68 },
      { label: 'Enerji', amount: 1500, sharePct: 13 },
      { label: 'İşçilik', amount: 1000, sharePct: 8 },
      { label: 'Paketleme', amount: 600, sharePct: 5 },
      { label: 'Nakliye', amount: 400, sharePct: 3 },
      { label: 'Diğer', amount: 300, sharePct: 3 },
    ],
    yieldPerDekar: 0,
    yieldUnit: 'kg',
    profitabilityRatio: 1.12,
    efficiencyScore: 65,
    region: 'Marmara / İç Anadolu',
    harvestMonths: 'Eyl — Mar',
  },
  {
    id: 'kultur-mantari',
    name: 'Kültür Mantarı',
    category: 'Mantarlar',
    icon: 'Circle',
    unit: '₺/kg',
    price: 109.35,
    changeDay: 0.8,
    changeWeek: 1.6,
    changeMonth: 3.5,
    changeYear: 13.2,
    history: makeSeries(214, 30, 100, 3),
    priceHistory: makeDatedSeries(214, 120, 98, 4),
    costBreakdown: [
      { label: 'Kompost/Miselyum', amount: 28000, sharePct: 50 },
      { label: 'İklimlendirme', amount: 12000, sharePct: 21 },
      { label: 'İşçilik', amount: 8000, sharePct: 14 },
      { label: 'Su', amount: 4000, sharePct: 7 },
      { label: 'Paketleme', amount: 2500, sharePct: 5 },
      { label: 'Diğer', amount: 1500, sharePct: 3 },
    ],
    yieldPerDekar: 0,
    yieldUnit: 'kg/m²',
    profitabilityRatio: 1.34,
    efficiencyScore: 76,
    region: 'İç Anadolu / Marmara',
    harvestMonths: 'Yıl boyu',
  },
  {
    id: 'istiridye-mantari',
    name: 'İstiridye Mantarı',
    category: 'Mantarlar',
    icon: 'Circle',
    unit: '₺/kg',
    price: 135.0,
    changeDay: 0.6,
    changeWeek: 1.4,
    changeMonth: 4.1,
    changeYear: 16.8,
    history: makeSeries(601, 30, 122, 3.5),
    priceHistory: makeDatedSeries(601, 120, 115, 5.0),
    costBreakdown: [
      { label: 'Kompost (Saman/Talaş) & Misel', amount: 32000, sharePct: 46 },
      { label: 'Nem ve Havalandırma Enerjisi', amount: 16000, sharePct: 23 },
      { label: 'Hasat & İşçilik', amount: 11000, sharePct: 16 },
      { label: 'Viyol & Streç Paketleme', amount: 5500, sharePct: 8 },
      { label: 'Hijyen & Dezenfeksiyon', amount: 3000, sharePct: 4 },
      { label: 'Diğer', amount: 2000, sharePct: 3 },
    ],
    yieldPerDekar: 0,
    yieldUnit: 'kg/m²',
    profitabilityRatio: 1.42,
    efficiencyScore: 80,
    region: 'Marmara / İç Anadolu / Ege',
    harvestMonths: 'Yıl boyu',
  },
  {
    id: 'sitaki-aslan-yelesi-mantari',
    name: 'Şitaki & Aslan Yelesi Mantarı',
    category: 'Mantarlar',
    icon: 'Sparkles',
    unit: '₺/kg',
    price: 420.0,
    changeDay: 0.9,
    changeWeek: 2.5,
    changeMonth: 6.8,
    changeYear: 28.5,
    history: makeSeries(602, 30, 380, 8.0),
    priceHistory: makeDatedSeries(602, 120, 350, 12.0),
    costBreakdown: [
      { label: 'Meşe Talaşı/Özel Substrat & Misel', amount: 58000, sharePct: 42 },
      { label: 'Hassas İklimlendirme & HEPA Filtre', amount: 36000, sharePct: 26 },
      { label: 'Laboratuvar ve Sterilizasyon', amount: 20000, sharePct: 15 },
      { label: 'Hassas Hasat İşçiliği', amount: 12500, sharePct: 9 },
      { label: 'Bariyerli Özel Ambalaj', amount: 7500, sharePct: 5 },
      { label: 'Diğer', amount: 4000, sharePct: 3 },
    ],
    yieldPerDekar: 0,
    yieldUnit: 'kg/m²',
    profitabilityRatio: 1.65,
    efficiencyScore: 74,
    region: 'Marmara / Karadeniz',
    harvestMonths: 'Yıl boyu',
  },
  {
    id: 'kral-istiridye-mantari',
    name: 'Kral İstiridye Mantarı (King Oyster)',
    category: 'Mantarlar',
    icon: 'CircleDot',
    unit: '₺/kg',
    price: 260.0,
    changeDay: 0.4,
    changeWeek: 1.8,
    changeMonth: 5.0,
    changeYear: 22.0,
    history: makeSeries(603, 30, 235, 6.0),
    priceHistory: makeDatedSeries(603, 120, 220, 8.5),
    costBreakdown: [
      { label: 'Şişe/Torba Substrat & Miselyum', amount: 44000, sharePct: 44 },
      { label: 'Sıcaklık/Nem & CO2 Kontrolü', amount: 25000, sharePct: 25 },
      { label: 'Otoklav & Sterilizasyon Enerjisi', amount: 14000, sharePct: 14 },
      { label: 'İşçilik', amount: 9000, sharePct: 9 },
      { label: 'Paketleme & Etiketleme', amount: 5000, sharePct: 5 },
      { label: 'Diğer', amount: 3000, sharePct: 3 },
    ],
    yieldPerDekar: 0,
    yieldUnit: 'kg/m²',
    profitabilityRatio: 1.50,
    efficiencyScore: 78,
    region: 'Marmara / Ege',
    harvestMonths: 'Yıl boyu',
  },
  {
    id: 'kestane-mantari',
    name: 'Kestane Mantarı (Kahverengi Agaricus)',
    category: 'Mantarlar',
    icon: 'Circle',
    unit: '₺/kg',
    price: 145.0,
    changeDay: 0.5,
    changeWeek: 1.2,
    changeMonth: 3.8,
    changeYear: 15.5,
    history: makeSeries(604, 30, 132, 3.0),
    priceHistory: makeDatedSeries(604, 120, 125, 4.5),
    costBreakdown: [
      { label: 'Kahverengi Misel & Pastörize Kompost', amount: 34000, sharePct: 48 },
      { label: 'Örtü Toprağı & Sulama', amount: 16000, sharePct: 23 },
      { label: 'İklimlendirme (Oda Sıcaklığı/Nem)', amount: 10500, sharePct: 15 },
      { label: 'Toplama İşçiliği', amount: 5500, sharePct: 8 },
      { label: 'Kutu & Paketleme', amount: 3000, sharePct: 4 },
      { label: 'Diğer', amount: 1500, sharePct: 2 },
    ],
    yieldPerDekar: 0,
    yieldUnit: 'kg/m²',
    profitabilityRatio: 1.38,
    efficiencyScore: 82,
    region: 'İç Anadolu / Akdeniz (Korkuteli)',
    harvestMonths: 'Yıl boyu',
  },
  {
    id: 'sap-saman',
    name: 'Sap ve Saman',
    category: 'Tarımsal Yan Ürünler ve Atıklar',
    icon: 'Wheat',
    unit: '₺/kg',
    price: 4.5,
    changeDay: 0.1,
    changeWeek: 0.4,
    changeMonth: 1.2,
    changeYear: 5.8,
    history: makeSeries(215, 30, 4.2, 0.15),
    priceHistory: makeDatedSeries(215, 120, 4, 0.2),
    costBreakdown: [
      { label: 'Balya/İşçilik', amount: 1800, sharePct: 45 },
      { label: 'Nakliye', amount: 1200, sharePct: 30 },
      { label: 'Ekipman/Yakıt', amount: 800, sharePct: 20 },
      { label: 'Depolama', amount: 1200, sharePct: 30 },
      { label: 'Diğer', amount: 500, sharePct: 12 },
    ],
    yieldPerDekar: 400,
    yieldUnit: 'kg',
    profitabilityRatio: 1.08,
    efficiencyScore: 60,
    region: 'İç Anadolu',
    harvestMonths: 'Haz — Ağu',
  },
  {
    id: 'aniz-saman',
    name: 'Anız ve Saman',
    category: 'Tarımsal Yan Ürünler ve Atıklar',
    icon: 'Wheat',
    unit: '₺/kg',
    price: 3.8,
    changeDay: 0.1,
    changeWeek: 0.5,
    changeMonth: 1.8,
    changeYear: 8.5,
    history: makeSeries(501, 30, 3.5, 0.1),
    priceHistory: makeDatedSeries(501, 120, 3.2, 0.15),
    costBreakdown: [
      { label: 'Balya & İp Maliyeti', amount: 1200, sharePct: 38 },
      { label: 'Nakliye / Lojistik', amount: 1000, sharePct: 31 },
      { label: 'Traktör Yakıtı & Ekipman', amount: 600, sharePct: 19 },
      { label: 'İşçilik (Yükleme)', amount: 400, sharePct: 12 },
    ],
    yieldPerDekar: 350,
    yieldUnit: 'kg',
    profitabilityRatio: 1.12,
    efficiencyScore: 65,
    region: 'İç Anadolu / Güneydoğu',
    harvestMonths: 'Haz — Ağu',
  },
  {
    id: 'misir-somegi-sapi',
    name: 'Mısır Sömeği ve Sapı',
    category: 'Tarımsal Yan Ürünler ve Atıklar',
    icon: 'Layers',
    unit: '₺/kg',
    price: 2.9,
    changeDay: 0.0,
    changeWeek: 0.3,
    changeMonth: 1.1,
    changeYear: 6.2,
    history: makeSeries(502, 30, 2.7, 0.08),
    priceHistory: makeDatedSeries(502, 120, 2.5, 0.12),
    costBreakdown: [
      { label: 'Kırma & Parçalama', amount: 950, sharePct: 35 },
      { label: 'Toplama & Balyalama', amount: 850, sharePct: 31 },
      { label: 'Nakliye', amount: 600, sharePct: 22 },
      { label: 'Depolama/Fire', amount: 300, sharePct: 12 },
    ],
    yieldPerDekar: 550,
    yieldUnit: 'kg',
    profitabilityRatio: 1.15,
    efficiencyScore: 70,
    region: 'Akdeniz / Ege / Marmara',
    harvestMonths: 'Eyl — Kas',
  },
  {
    id: 'pamuk-copu-telef',
    name: 'Pamuk Çöpü (Telef)',
    category: 'Tarımsal Yan Ürünler ve Atıklar',
    icon: 'Sparkles',
    unit: '₺/kg',
    price: 4.2,
    changeDay: 0.2,
    changeWeek: 0.7,
    changeMonth: 2.0,
    changeYear: 10.4,
    history: makeSeries(503, 30, 3.9, 0.12),
    priceHistory: makeDatedSeries(503, 120, 3.6, 0.18),
    costBreakdown: [
      { label: 'Çırçır Ayrıştırma İşlemi', amount: 1400, sharePct: 40 },
      { label: 'Presleme & Paketleme', amount: 1000, sharePct: 29 },
      { label: 'Nakliye', amount: 700, sharePct: 20 },
      { label: 'İşçilik', amount: 400, sharePct: 11 },
    ],
    yieldPerDekar: 180,
    yieldUnit: 'kg',
    profitabilityRatio: 1.18,
    efficiencyScore: 72,
    region: 'Ege / Güneydoğu / Çukurova',
    harvestMonths: 'Eki — Ara',
  },
  {
    id: 'budama-artiklari',
    name: 'Budama Artıkları (Biyokütle)',
    category: 'Tarımsal Yan Ürünler ve Atıklar',
    icon: 'Trees',
    unit: '₺/kg',
    price: 2.2,
    changeDay: 0.1,
    changeWeek: 0.2,
    changeMonth: 0.9,
    changeYear: 5.0,
    history: makeSeries(504, 30, 2.0, 0.05),
    priceHistory: makeDatedSeries(504, 120, 1.9, 0.1),
    costBreakdown: [
      { label: 'Dal Öğütme & Yontma', amount: 800, sharePct: 42 },
      { label: 'Toplama İşçiliği', amount: 550, sharePct: 29 },
      { label: 'Nakliye', amount: 350, sharePct: 19 },
      { label: 'Depolama/Kurutma', amount: 200, sharePct: 10 },
    ],
    yieldPerDekar: 250,
    yieldUnit: 'kg',
    profitabilityRatio: 1.10,
    efficiencyScore: 68,
    region: 'Ege / Akdeniz / Marmara',
    harvestMonths: 'Oca — Mar',
  },
  {
    id: 'aycicegi-kafasi',
    name: 'Ayçiçeği Kafası ve Sapı',
    category: 'Tarımsal Yan Ürünler ve Atıklar',
    icon: 'Sun',
    unit: '₺/kg',
    price: 3.1,
    changeDay: 0.0,
    changeWeek: 0.4,
    changeMonth: 1.5,
    changeYear: 7.2,
    history: makeSeries(505, 30, 2.9, 0.08),
    priceHistory: makeDatedSeries(505, 120, 2.7, 0.14),
    costBreakdown: [
      { label: 'Toplama & Peletleme Hazırlığı', amount: 1100, sharePct: 39 },
      { label: 'Kurutma / Nem Kontrolü', amount: 800, sharePct: 28 },
      { label: 'Nakliye', amount: 600, sharePct: 21 },
      { label: 'İşçilik', amount: 350, sharePct: 12 },
    ],
    yieldPerDekar: 320,
    yieldUnit: 'kg',
    profitabilityRatio: 1.14,
    efficiencyScore: 74,
    region: 'Trakya / İç Anadolu',
    harvestMonths: 'Ağu — Eyl',
  },
  {
    id: 'zeytin-prinasi',
    name: 'Zeytin Prinası (Kuru/Pelet)',
    category: 'Tarımsal Yan Ürünler ve Atıklar',
    icon: 'Flame',
    unit: '₺/kg',
    price: 5.6,
    changeDay: 0.3,
    changeWeek: 1.0,
    changeMonth: 3.2,
    changeYear: 14.5,
    history: makeSeries(506, 30, 5.1, 0.15),
    priceHistory: makeDatedSeries(506, 120, 4.8, 0.25),
    costBreakdown: [
      { label: 'Kurutma & Yağ Ekstraksiyonu', amount: 1800, sharePct: 45 },
      { label: 'Peletleme Enerjisi', amount: 1000, sharePct: 25 },
      { label: 'Lojistik & Taşıma', amount: 700, sharePct: 18 },
      { label: 'Paketleme/Çuval', amount: 500, sharePct: 12 },
    ],
    yieldPerDekar: 0,
    yieldUnit: 'kg',
    profitabilityRatio: 1.28,
    efficiencyScore: 82,
    region: 'Ege / Marmara / Akdeniz',
    harvestMonths: 'Kas — Şub',
  },
  {
    id: 'zeytin-karasuyu',
    name: 'Zeytin Karasuyu (Arıtılmış Konsantre)',
    category: 'Tarımsal Yan Ürünler ve Atıklar',
    icon: 'Droplets',
    unit: '₺/kg',
    price: 1.8,
    changeDay: 0.0,
    changeWeek: 0.2,
    changeMonth: 0.5,
    changeYear: 4.0,
    history: makeSeries(507, 30, 1.7, 0.04),
    priceHistory: makeDatedSeries(507, 120, 1.6, 0.08),
    costBreakdown: [
      { label: 'Buharlaştırma & Konsantrasyon', amount: 750, sharePct: 47 },
      { label: 'Depolama Tankları', amount: 400, sharePct: 25 },
      { label: 'Vidanjör/Tanker Nakliyesi', amount: 300, sharePct: 19 },
      { label: 'Analiz & Arıtma', amount: 150, sharePct: 9 },
    ],
    yieldPerDekar: 0,
    yieldUnit: 'kg',
    profitabilityRatio: 1.06,
    efficiencyScore: 58,
    region: 'Ege / Marmara',
    harvestMonths: 'Kas — Şub',
  },
  {
    id: 'seker-pancari-kuspesi',
    name: 'Şeker Pancarı Küspesi (Silaj/Kuru)',
    category: 'Tarımsal Yan Ürünler ve Atıklar',
    icon: 'Layers',
    unit: '₺/kg',
    price: 4.8,
    changeDay: 0.2,
    changeWeek: 0.8,
    changeMonth: 2.4,
    changeYear: 11.2,
    history: makeSeries(508, 30, 4.4, 0.12),
    priceHistory: makeDatedSeries(508, 120, 4.1, 0.2),
    costBreakdown: [
      { label: 'Presleme & Kurutma', amount: 1600, sharePct: 42 },
      { label: 'Paketleme/Silaj Poşeti', amount: 1000, sharePct: 26 },
      { label: 'Nakliye', amount: 800, sharePct: 21 },
      { label: 'Yükleme İşçiliği', amount: 400, sharePct: 11 },
    ],
    yieldPerDekar: 0,
    yieldUnit: 'kg',
    profitabilityRatio: 1.22,
    efficiencyScore: 84,
    region: 'İç Anadolu',
    harvestMonths: 'Eki — Oca',
  },
  {
    id: 'melas',
    name: 'Melas',
    category: 'Tarımsal Yan Ürünler ve Atıklar',
    icon: 'Droplet',
    unit: '₺/kg',
    price: 8.5,
    changeDay: 0.3,
    changeWeek: 1.1,
    changeMonth: 3.0,
    changeYear: 16.0,
    history: makeSeries(509, 30, 7.8, 0.2),
    priceHistory: makeDatedSeries(509, 120, 7.2, 0.35),
    costBreakdown: [
      { label: 'Rafinasyon & Yoğunlaştırma', amount: 2600, sharePct: 40 },
      { label: 'Özel Tank Depolama', amount: 1800, sharePct: 28 },
      { label: 'Lojistik/Tanker', amount: 1400, sharePct: 21 },
      { label: 'Kalite & Şeker Analizi', amount: 700, sharePct: 11 },
    ],
    yieldPerDekar: 0,
    yieldUnit: 'kg',
    profitabilityRatio: 1.34,
    efficiencyScore: 88,
    region: 'İç Anadolu',
    harvestMonths: 'Eki — Oca',
  },
  {
    id: 'meyve-sebze-posasi',
    name: 'Meyve ve Sebze Posası (Kurutulmuş)',
    category: 'Tarımsal Yan Ürünler ve Atıklar',
    icon: 'Apple',
    unit: '₺/kg',
    price: 6.2,
    changeDay: 0.1,
    changeWeek: 0.6,
    changeMonth: 2.1,
    changeYear: 12.0,
    history: makeSeries(510, 30, 5.7, 0.16),
    priceHistory: makeDatedSeries(510, 120, 5.3, 0.22),
    costBreakdown: [
      { label: 'Kurutma Fırını Enerjisi', amount: 2200, sharePct: 48 },
      { label: 'Presleme ve Sıkma', amount: 1100, sharePct: 24 },
      { label: 'Nakliye / Fabrika Çıkışı', amount: 800, sharePct: 17 },
      { label: 'Paketleme', amount: 500, sharePct: 11 },
    ],
    yieldPerDekar: 0,
    yieldUnit: 'kg',
    profitabilityRatio: 1.25,
    efficiencyScore: 78,
    region: 'Akdeniz / Ege / Marmara',
    harvestMonths: 'Tem — Kas',
  },
  {
    id: 'findik-ceviz-kabugu',
    name: 'Fındık ve Ceviz Kabuğu',
    category: 'Tarımsal Yan Ürünler ve Atıklar',
    icon: 'Nut',
    unit: '₺/kg',
    price: 7.5,
    changeDay: 0.2,
    changeWeek: 0.9,
    changeMonth: 2.8,
    changeYear: 18.0,
    history: makeSeries(511, 30, 6.8, 0.22),
    priceHistory: makeDatedSeries(511, 120, 6.2, 0.3),
    costBreakdown: [
      { label: 'Kırma & Kabuk Eleme', amount: 2100, sharePct: 38 },
      { label: 'Kalibrasyon & Boylama', amount: 1500, sharePct: 27 },
      { label: 'Nakliye (Yakıt Sektörüne)', amount: 1200, sharePct: 22 },
      { label: 'Çuvallama', amount: 700, sharePct: 13 },
    ],
    yieldPerDekar: 0,
    yieldUnit: 'kg',
    profitabilityRatio: 1.36,
    efficiencyScore: 86,
    region: 'Karadeniz / Ege',
    harvestMonths: 'Ağu — Kas',
  },
  {
    id: 'celtik-kavuzu',
    name: 'Çeltik (Pirinç) Kavuzu',
    category: 'Tarımsal Yan Ürünler ve Atıklar',
    icon: 'Wheat',
    unit: '₺/kg',
    price: 3.4,
    changeDay: 0.1,
    changeWeek: 0.4,
    changeMonth: 1.6,
    changeYear: 9.0,
    history: makeSeries(512, 30, 3.1, 0.09),
    priceHistory: makeDatedSeries(512, 120, 2.9, 0.15),
    costBreakdown: [
      { label: 'Kabuk Soyma & Ayrıştırma', amount: 1200, sharePct: 43 },
      { label: 'Depolama Silosu', amount: 700, sharePct: 25 },
      { label: 'Nakliye', amount: 600, sharePct: 21 },
      { label: 'Yükleme', amount: 300, sharePct: 11 },
    ],
    yieldPerDekar: 0,
    yieldUnit: 'kg',
    profitabilityRatio: 1.16,
    efficiencyScore: 76,
    region: 'Marmara (Trakya) / Karadeniz',
    harvestMonths: 'Eyl — Kas',
  },
  {
    id: 'pirinc-kepegi',
    name: 'Pirinç Kepeği (Stabilize)',
    category: 'Tarımsal Yan Ürünler ve Atıklar',
    icon: 'Sparkles',
    unit: '₺/kg',
    price: 9.2,
    changeDay: 0.4,
    changeWeek: 1.3,
    changeMonth: 3.5,
    changeYear: 19.5,
    history: makeSeries(513, 30, 8.3, 0.25),
    priceHistory: makeDatedSeries(513, 120, 7.6, 0.4),
    costBreakdown: [
      { label: 'Isıl Stabilizasyon (Enzim İnhibisyonu)', amount: 2900, sharePct: 42 },
      { label: 'Yağ Oksidasyon Koruması', amount: 1700, sharePct: 25 },
      { label: 'Hava Almaz Ambalaj', amount: 1300, sharePct: 19 },
      { label: 'Nakliye', amount: 1000, sharePct: 14 },
    ],
    yieldPerDekar: 0,
    yieldUnit: 'kg',
    profitabilityRatio: 1.38,
    efficiencyScore: 83,
    region: 'Marmara / Karadeniz',
    harvestMonths: 'Eyl — Kas',
  },
  {
    id: 'meyve-cekirdekleri',
    name: 'Meyve Çekirdekleri (Kayısı/Şeftali)',
    category: 'Tarımsal Yan Ürünler ve Atıklar',
    icon: 'CircleDot',
    unit: '₺/kg',
    price: 24.0,
    changeDay: 0.5,
    changeWeek: 1.8,
    changeMonth: 4.6,
    changeYear: 22.0,
    history: makeSeries(514, 30, 21.5, 0.6),
    priceHistory: makeDatedSeries(514, 120, 19.5, 0.9),
    costBreakdown: [
      { label: 'Kurutma & Yıkama/Et Ayrımı', amount: 6200, sharePct: 40 },
      { label: 'Kabuk Kırma & İç Eleme', amount: 4400, sharePct: 28 },
      { label: 'Sınıflandırma ve Ayıklama', amount: 3100, sharePct: 20 },
      { label: 'Paketleme/Çuval', amount: 1800, sharePct: 12 },
    ],
    yieldPerDekar: 0,
    yieldUnit: 'kg',
    profitabilityRatio: 1.48,
    efficiencyScore: 80,
    region: 'Doğu Anadolu (Malatya) / Ege',
    harvestMonths: 'Tem — Eyl',
  },
  {
    id: 'kakao-kahve-kabuklari',
    name: 'Kakao ve Kahve Kabukları (Cascara)',
    category: 'Tarımsal Yan Ürünler ve Atıklar',
    icon: 'Coffee',
    unit: '₺/kg',
    price: 85.0,
    changeDay: 0.6,
    changeWeek: 2.1,
    changeMonth: 5.4,
    changeYear: 26.5,
    history: makeSeries(515, 30, 76.0, 1.8),
    priceHistory: makeDatedSeries(515, 120, 70.0, 2.5),
    costBreakdown: [
      { label: 'Kavurma & Kabuk Ayırma/Hava Sistemi', amount: 24000, sharePct: 44 },
      { label: 'Gıda Güvenliği & Mikrobiyoloji Testleri', amount: 14000, sharePct: 25 },
      { label: 'Özel Nem Bariyerli Ambalaj', amount: 9500, sharePct: 17 },
      { label: 'İşçilik & Paketleme', amount: 7500, sharePct: 14 },
    ],
    yieldPerDekar: 0,
    yieldUnit: 'kg',
    profitabilityRatio: 1.55,
    efficiencyScore: 78,
    region: 'Marmara / Ege (İşleme Tesisleri)',
    harvestMonths: 'Yıl boyu',
  },
  {
    id: 'sertifikali-tohum',
    name: 'Sertifikalı Tohum',
    category: 'Tohumluk ve Fidan',
    icon: 'Sprout',
    unit: '₺/kg',
    price: 65,
    changeDay: 0.5,
    changeWeek: 1.2,
    changeMonth: 3.0,
    changeYear: 11.4,
    history: makeSeries(216, 30, 60, 1.5),
    priceHistory: makeDatedSeries(216, 120, 58, 2),
    costBreakdown: [
      { label: 'Araştırma/ISLAH', amount: 22000, sharePct: 44 },
      { label: 'Üretim/Tohumluk', amount: 15000, sharePct: 30 },
      { label: 'Sertifika/Kontrol', amount: 6000, sharePct: 12 },
      { label: 'İşçilik', amount: 4000, sharePct: 8 },
      { label: 'Paketleme', amount: 2000, sharePct: 4 },
      { label: 'Diğer', amount: 1000, sharePct: 2 },
    ],
    yieldPerDekar: 350,
    yieldUnit: 'kg',
    profitabilityRatio: 1.30,
    efficiencyScore: 78,
    region: 'İç Anadolu / Karadeniz',
    harvestMonths: 'Haz — Tem',
  },
  {
    id: 'mavi-sertifikali-fidan',
    name: 'Mavi Sertifikalı Ceviz & Badem Fidanı',
    category: 'Tohumluk ve Fidan',
    icon: 'Trees',
    unit: '₺/adet',
    price: 240,
    changeDay: 0.2,
    changeWeek: 0.9,
    changeMonth: 2.5,
    changeYear: 15.0,
    history: makeSeries(401, 30, 220, 4.0),
    priceHistory: makeDatedSeries(401, 120, 210, 6.0),
    costBreakdown: [
      { label: 'Damızlık/Anaç & Aşı Gözü', amount: 35000, sharePct: 38 },
      { label: 'Doku Kültürü & Islah', amount: 22000, sharePct: 24 },
      { label: 'Mavi Sertifikasyon & Analiz', amount: 15000, sharePct: 16 },
      { label: 'Aşılama ve Budama İşçiliği', amount: 11000, sharePct: 12 },
      { label: 'Tüp/Torba & Harç Materyali', amount: 5500, sharePct: 6 },
      { label: 'Karantina & Diğer', amount: 3500, sharePct: 4 },
    ],
    yieldPerDekar: 1800,
    yieldUnit: 'adet',
    profitabilityRatio: 1.45,
    efficiencyScore: 86,
    region: 'Ege / Marmara / Güneydoğu',
    harvestMonths: 'Kas — Mar',
  },
  {
    id: 'aronya-yaban-mersini-fidani',
    name: 'Aronya & Yaban Mersini Fidanı',
    category: 'Tohumluk ve Fidan',
    icon: 'Cherry',
    unit: '₺/adet',
    price: 185,
    changeDay: 0.4,
    changeWeek: 1.5,
    changeMonth: 3.8,
    changeYear: 21.0,
    history: makeSeries(402, 30, 165, 3.5),
    priceHistory: makeDatedSeries(402, 120, 150, 5.0),
    costBreakdown: [
      { label: 'Doku Kültürü/Mikro Çoğaltım', amount: 32000, sharePct: 40 },
      { label: 'Özel Asidik Torf & Perlit', amount: 18000, sharePct: 22 },
      { label: 'Sera/İklimlendirme', amount: 13000, sharePct: 16 },
      { label: 'Bakım & Aşılama İşçiliği', amount: 9500, sharePct: 12 },
      { label: 'Sertifika & Kontrol', amount: 5000, sharePct: 6 },
      { label: 'Diğer', amount: 3500, sharePct: 4 },
    ],
    yieldPerDekar: 2200,
    yieldUnit: 'adet',
    profitabilityRatio: 1.52,
    efficiencyScore: 82,
    region: 'Karadeniz / Marmara',
    harvestMonths: 'Eki — Nis',
  },
  {
    id: 'ejder-meyvesi-celigi',
    name: 'Ejder Meyvesi (Pitaya) Çeliği',
    category: 'Tohumluk ve Fidan',
    icon: 'Flame',
    unit: '₺/adet',
    price: 95,
    changeDay: 0.1,
    changeWeek: 0.8,
    changeMonth: 2.1,
    changeYear: 12.5,
    history: makeSeries(403, 30, 88, 2.0),
    priceHistory: makeDatedSeries(403, 120, 82, 3.0),
    costBreakdown: [
      { label: 'Damızlık Çelik Materyali', amount: 28000, sharePct: 42 },
      { label: 'Köklendirme Hormon & Ortamı', amount: 16000, sharePct: 24 },
      { label: 'Sera Isıtma & Nem Kontrolü', amount: 11000, sharePct: 16 },
      { label: 'Kesim ve Dikim İşçiliği', amount: 7000, sharePct: 10 },
      { label: 'Tüpleme & Paketleme', amount: 3500, sharePct: 5 },
      { label: 'Diğer', amount: 2000, sharePct: 3 },
    ],
    yieldPerDekar: 3000,
    yieldUnit: 'adet',
    profitabilityRatio: 1.38,
    efficiencyScore: 80,
    region: 'Akdeniz / Ege',
    harvestMonths: 'Nis — Eyl',
  },
  {
    id: 'truf-asili-mese-fidani',
    name: 'Trüf Aşılı Meşe Fidanı',
    category: 'Tohumluk ve Fidan',
    icon: 'Trees',
    unit: '₺/adet',
    price: 550,
    changeDay: 0.8,
    changeWeek: 2.2,
    changeMonth: 5.0,
    changeYear: 28.0,
    history: makeSeries(404, 30, 480, 10.0),
    priceHistory: makeDatedSeries(404, 120, 440, 15.0),
    costBreakdown: [
      { label: 'Trüf Spor İnokülasyonu', amount: 65000, sharePct: 48 },
      { label: 'DNA/Mikroskopik Kolonizasyon Testi', amount: 28000, sharePct: 21 },
      { label: 'Steril Toprak & Özel Substrat', amount: 19000, sharePct: 14 },
      { label: 'Laboratuvar İşçiliği', amount: 13500, sharePct: 10 },
      { label: 'Sertifikasyon', amount: 6000, sharePct: 4 },
      { label: 'Diğer', amount: 4000, sharePct: 3 },
    ],
    yieldPerDekar: 1200,
    yieldUnit: 'adet',
    profitabilityRatio: 1.75,
    efficiencyScore: 72,
    region: 'Ege / Marmara / Karadeniz',
    harvestMonths: 'Kas — Şub',
  },
  {
    id: 'tuplu-avokado-fidani',
    name: 'Tüplü Avokado Fidanı',
    category: 'Tohumluk ve Fidan',
    icon: 'Sprout',
    unit: '₺/adet',
    price: 280,
    changeDay: 0.3,
    changeWeek: 1.1,
    changeMonth: 3.4,
    changeYear: 18.0,
    history: makeSeries(405, 30, 255, 5.0),
    priceHistory: makeDatedSeries(405, 120, 240, 8.0),
    costBreakdown: [
      { label: 'Klon Anaç & Kalem', amount: 38000, sharePct: 39 },
      { label: 'Aşılama & Uyum Süreci', amount: 24000, sharePct: 25 },
      { label: 'Özel Torf/Tüpleme', amount: 16000, sharePct: 16 },
      { label: 'Sera Bakım İşçiliği', amount: 11000, sharePct: 11 },
      { label: 'Fito-Sertifika', amount: 5000, sharePct: 5 },
      { label: 'Diğer', amount: 4000, sharePct: 4 },
    ],
    yieldPerDekar: 1500,
    yieldUnit: 'adet',
    profitabilityRatio: 1.48,
    efficiencyScore: 84,
    region: 'Akdeniz (Antalya / Mersin)',
    harvestMonths: 'Yıl boyu',
  },
  {
    id: 'kinoa-karabugday-tohumlugu',
    name: 'Kinoa & Karabuğday Tohumluğu',
    category: 'Tohumluk ve Fidan',
    icon: 'Wheat',
    unit: '₺/kg',
    price: 145,
    changeDay: 0.5,
    changeWeek: 1.4,
    changeMonth: 3.6,
    changeYear: 16.8,
    history: makeSeries(406, 30, 132, 2.5),
    priceHistory: makeDatedSeries(406, 120, 125, 3.5),
    costBreakdown: [
      { label: 'Orijinal Islah Tohumu', amount: 30000, sharePct: 40 },
      { label: 'Selektör & Boylama', amount: 18000, sharePct: 24 },
      { label: 'Çimlenme & Saflık Testi', amount: 12000, sharePct: 16 },
      { label: 'İlaçlama/Kaplama', amount: 8000, sharePct: 11 },
      { label: 'Bez Çuval/Paketleme', amount: 4500, sharePct: 6 },
      { label: 'Diğer', amount: 2500, sharePct: 3 },
    ],
    yieldPerDekar: 280,
    yieldUnit: 'kg',
    profitabilityRatio: 1.42,
    efficiencyScore: 85,
    region: 'İç Anadolu / Karadeniz',
    harvestMonths: 'Ağu — Eki',
  },
  {
    id: 'tibbi-papatya-lavanta-tohumu',
    name: 'Tıbbi Papatya & Lavanta Tohumu',
    category: 'Tohumluk ve Fidan',
    icon: 'Flower2',
    unit: '₺/kg',
    price: 920,
    changeDay: 0.6,
    changeWeek: 1.9,
    changeMonth: 4.8,
    changeYear: 23.5,
    history: makeSeries(407, 30, 840, 15.0),
    priceHistory: makeDatedSeries(407, 120, 800, 20.0),
    costBreakdown: [
      { label: 'Uçucu Yağ Değeri Yüksek Islah', amount: 52000, sharePct: 45 },
      { label: 'Hassas Eleme/Kalibrasyon', amount: 24000, sharePct: 21 },
      { label: 'El Hasadı/Ayıklama İşçiliği', amount: 18000, sharePct: 16 },
      { label: 'Laboratuvar ve Etken Madde Testi', amount: 12000, sharePct: 10 },
      { label: 'Havasız Özel Paketleme', amount: 6000, sharePct: 5 },
      { label: 'Diğer', amount: 3500, sharePct: 3 },
    ],
    yieldPerDekar: 60,
    yieldUnit: 'kg',
    profitabilityRatio: 1.65,
    efficiencyScore: 78,
    region: 'Ege / Akdeniz / İç Anadolu',
    harvestMonths: 'Tem — Eyl',
  },
  {
    id: 'yerli-atalik-tohum',
    name: 'Yerli ve Atalık Tohum Üretimi',
    category: 'Tohumluk ve Fidan',
    icon: 'Sprout',
    unit: '₺/kg',
    price: 480,
    changeDay: 0.4,
    changeWeek: 1.0,
    changeMonth: 2.8,
    changeYear: 20.0,
    history: makeSeries(408, 30, 435, 8.0),
    priceHistory: makeDatedSeries(408, 120, 410, 12.0),
    costBreakdown: [
      { label: 'İzolasyon Tarlası & Yetiştiricilik', amount: 42000, sharePct: 42 },
      { label: 'Genetik Saflık Takibi', amount: 23000, sharePct: 23 },
      { label: 'Geleneksel Hasat & Ayıklama', amount: 17000, sharePct: 17 },
      { label: 'Gölgede Kurutma & Saklama', amount: 10000, sharePct: 10 },
      { label: 'Etiketleme & Bez Kese', amount: 5000, sharePct: 5 },
      { label: 'Diğer', amount: 3000, sharePct: 3 },
    ],
    yieldPerDekar: 90,
    yieldUnit: 'kg',
    profitabilityRatio: 1.55,
    efficiencyScore: 75,
    region: 'Ege / Marmara / İç Anadolu',
    harvestMonths: 'Ağu — Eki',
  },
  {
    id: 'yem-bitkileri-tohumlugu',
    name: 'Yem Bitkileri Tohumluğu (Yonca & Korunga)',
    category: 'Tohumluk ve Fidan',
    icon: 'Wheat',
    unit: '₺/kg',
    price: 115,
    changeDay: 0.3,
    changeWeek: 0.7,
    changeMonth: 2.0,
    changeYear: 13.5,
    history: makeSeries(409, 30, 106, 1.8),
    priceHistory: makeDatedSeries(409, 120, 102, 2.5),
    costBreakdown: [
      { label: 'Küsküt ve Yabancı Ot Temizleme', amount: 26000, sharePct: 37 },
      { label: 'Sertifikalı Üretim Tarlası', amount: 21000, sharePct: 30 },
      { label: 'Bakteri Aşılama/Kaplama', amount: 11000, sharePct: 16 },
      { label: 'Sertifika Denetim Harçları', amount: 6500, sharePct: 9 },
      { label: 'Paketleme', amount: 3500, sharePct: 5 },
      { label: 'Diğer', amount: 2000, sharePct: 3 },
    ],
    yieldPerDekar: 420,
    yieldUnit: 'kg',
    profitabilityRatio: 1.32,
    efficiencyScore: 88,
    region: 'İç Anadolu / Doğu Anadolu',
    harvestMonths: 'Tem — Ağu',
  },
  {
    id: 'mikroyesillik-tohumlari',
    name: 'Mikroyeşillik (Microgreens) Tohumları',
    category: 'Tohumluk ve Fidan',
    icon: 'Leaf',
    unit: '₺/kg',
    price: 360,
    changeDay: 0.7,
    changeWeek: 2.0,
    changeMonth: 4.5,
    changeYear: 22.0,
    history: makeSeries(410, 30, 325, 6.0),
    priceHistory: makeDatedSeries(410, 120, 305, 8.5),
    costBreakdown: [
      { label: 'İlaçsız/Pestisit Testli Üretim', amount: 38000, sharePct: 44 },
      { label: 'Yüksek Çimlenme Testleri (%98+)', amount: 22000, sharePct: 25 },
      { label: 'Mikro Kalibrasyon ve Temizlik', amount: 14000, sharePct: 16 },
      { label: 'İşçilik', amount: 7000, sharePct: 8 },
      { label: 'Nem Korumalı Bariyerli Ambalaj', amount: 4000, sharePct: 5 },
      { label: 'Diğer', amount: 2000, sharePct: 2 },
    ],
    yieldPerDekar: 200,
    yieldUnit: 'kg',
    profitabilityRatio: 1.60,
    efficiencyScore: 81,
    region: 'Marmara / Ege / Akdeniz',
    harvestMonths: 'Yıl boyu',
  },
  {
    id: 'spirulina',
    name: 'Spirulina',
    category: 'Yeni Nesil ve Alternatif Tarım',
    icon: 'Leaf',
    unit: '₺/kg',
    price: 850,
    changeDay: 1.2,
    changeWeek: 2.8,
    changeMonth: 6.0,
    changeYear: 19.5,
    history: makeSeries(217, 30, 780, 20),
    priceHistory: makeDatedSeries(217, 120, 750, 25),
    costBreakdown: [
      { label: 'Besin Çözeltisi', amount: 45000, sharePct: 42 },
      { label: 'İklimlendirme', amount: 28000, sharePct: 26 },
      { label: 'İşçilik', amount: 15000, sharePct: 14 },
      { label: 'Enerji', amount: 10000, sharePct: 9 },
      { label: 'Kuru/İşleme', amount: 6000, sharePct: 6 },
      { label: 'Diğer', amount: 3000, sharePct: 3 },
    ],
    yieldPerDekar: 0,
    yieldUnit: 'kg',
    profitabilityRatio: 1.44,
    efficiencyScore: 80,
    region: 'Akdeniz / Ege',
    harvestMonths: 'Yıl boyu',
  },
  {
    id: 'kinoa',
    name: 'Kinoa',
    category: 'Yeni Nesil ve Alternatif Tarım',
    icon: 'Sparkles',
    unit: '₺/kg',
    price: 95.0,
    changeDay: 0.6,
    changeWeek: 1.8,
    changeMonth: 4.2,
    changeYear: 24.5,
    history: makeSeries(301, 30, 88, 1.2),
    priceHistory: makeDatedSeries(301, 120, 80, 2.0),
    costBreakdown: [
      { label: 'Sertifikalı Tohum', amount: 1200, sharePct: 24 },
      { label: 'Saponin Arındırma/İşleme', amount: 1100, sharePct: 22 },
      { label: 'İşçilik (Hasat/Ayıklama)', amount: 950, sharePct: 19 },
      { label: 'Organik Gübreleme', amount: 800, sharePct: 16 },
      { label: 'Sulama/Enerji', amount: 550, sharePct: 11 },
      { label: 'Paketleme/Lojistik', amount: 400, sharePct: 8 },
    ],
    yieldPerDekar: 220,
    yieldUnit: 'kg',
    profitabilityRatio: 1.58,
    efficiencyScore: 84,
    region: 'İç Anadolu / Ege',
    harvestMonths: 'Ağu — Eyl',
  },
  {
    id: 'karabugday',
    name: 'Karabuğday (Greçka)',
    category: 'Yeni Nesil ve Alternatif Tarım',
    icon: 'Wheat',
    unit: '₺/kg',
    price: 68.0,
    changeDay: 0.3,
    changeWeek: 1.1,
    changeMonth: 3.5,
    changeYear: 18.2,
    history: makeSeries(302, 30, 62, 0.9),
    priceHistory: makeDatedSeries(302, 120, 56, 1.4),
    costBreakdown: [
      { label: 'Kabuk Soyma (Dehulling)', amount: 950, sharePct: 28 },
      { label: 'Tohum', amount: 750, sharePct: 22 },
      { label: 'Toprak Hazırlığı & Ekim', amount: 650, sharePct: 19 },
      { label: 'İşçilik', amount: 500, sharePct: 15 },
      { label: 'Gübreleme', amount: 350, sharePct: 10 },
      { label: 'Diğer', amount: 200, sharePct: 6 },
    ],
    yieldPerDekar: 180,
    yieldUnit: 'kg',
    profitabilityRatio: 1.48,
    efficiencyScore: 86,
    region: 'İç Anadolu / Karadeniz',
    harvestMonths: 'Tem — Ağu',
  },
  {
    id: 'teff',
    name: 'Teff Tohumu',
    category: 'Yeni Nesil ve Alternatif Tarım',
    icon: 'Dot',
    unit: '₺/kg',
    price: 135.0,
    changeDay: 0.8,
    changeWeek: 2.3,
    changeMonth: 5.6,
    changeYear: 28.0,
    history: makeSeries(303, 30, 122, 2.1),
    priceHistory: makeDatedSeries(303, 120, 110, 3.2),
    costBreakdown: [
      { label: 'Mikro Tohum Temini', amount: 1400, sharePct: 29 },
      { label: 'Hassas Eleme/Temizleme', amount: 1200, sharePct: 25 },
      { label: 'İşçilik & Hasat Kaybı Yönetimi', amount: 900, sharePct: 19 },
      { label: 'Sulama Kontrolü', amount: 650, sharePct: 14 },
      { label: 'Gübreleme', amount: 400, sharePct: 8 },
      { label: 'Paketleme', amount: 250, sharePct: 5 },
    ],
    yieldPerDekar: 140,
    yieldUnit: 'kg',
    profitabilityRatio: 1.62,
    efficiencyScore: 76,
    region: 'Ege / Akdeniz',
    harvestMonths: 'Ağu — Eyl',
  },
  {
    id: 'chia-tohumu',
    name: 'Chia Tohumu',
    category: 'Yeni Nesil ve Alternatif Tarım',
    icon: 'Sparkles',
    unit: '₺/kg',
    price: 160.0,
    changeDay: 0.5,
    changeWeek: 1.9,
    changeMonth: 6.2,
    changeYear: 31.5,
    history: makeSeries(304, 30, 145, 2.5),
    priceHistory: makeDatedSeries(304, 120, 130, 4.0),
    costBreakdown: [
      { label: 'İthal Tohum/Fide', amount: 1600, sharePct: 30 },
      { label: 'Hassas Hasat & Kurutma', amount: 1300, sharePct: 24 },
      { label: 'Damlama Sulama/Enerji', amount: 950, sharePct: 18 },
      { label: 'İşçilik', amount: 800, sharePct: 15 },
      { label: 'Gıda Güvenliği & Paketleme', amount: 450, sharePct: 8 },
      { label: 'Diğer', amount: 250, sharePct: 5 },
    ],
    yieldPerDekar: 110,
    yieldUnit: 'kg',
    profitabilityRatio: 1.68,
    efficiencyScore: 74,
    region: 'Akdeniz / Ege',
    harvestMonths: 'Eyl — Eki',
  },
  {
    id: 'amarant',
    name: 'Amarant (Horozibiği)',
    category: 'Yeni Nesil ve Alternatif Tarım',
    icon: 'Flower2',
    unit: '₺/kg',
    price: 120.0,
    changeDay: 0.4,
    changeWeek: 1.5,
    changeMonth: 4.8,
    changeYear: 26.0,
    history: makeSeries(305, 30, 108, 1.8),
    priceHistory: makeDatedSeries(305, 120, 98, 2.8),
    costBreakdown: [
      { label: 'Tohum & Ekim', amount: 1100, sharePct: 26 },
      { label: 'Hasat & Savurma İşçiliği', amount: 1000, sharePct: 24 },
      { label: 'Kurutma & Temizleme', amount: 850, sharePct: 20 },
      { label: 'Organik Gübre', amount: 600, sharePct: 14 },
      { label: 'Sulama', amount: 400, sharePct: 10 },
      { label: 'Diğer', amount: 250, sharePct: 6 },
    ],
    yieldPerDekar: 160,
    yieldUnit: 'kg',
    profitabilityRatio: 1.52,
    efficiencyScore: 79,
    region: 'İç Anadolu / Akdeniz',
    harvestMonths: 'Ağu — Eki',
  },
];

export interface ProductGroup {
  id: number;
  name: string;
  description: string;
  productIds: string[];
}

export const productGroups: ProductGroup[] = [
  { id: 1, name: 'Temel Hububat', description: 'Temel hububat ürünleri', productIds: ['bugday', 'misir'] },
  { id: 2, name: 'Temel Bakliyat', description: 'Bakla ve bezelye', productIds: ['bakla', 'bezelye'] },
  { id: 3, name: 'Diğer Bakliyat', description: 'Börülce ve burçak', productIds: ['borulce', 'burcak'] },
  { id: 4, name: 'Temel Yağlı Tohumlar', description: 'Ayçiçeği ve susam', productIds: ['aycicegi', 'susam'] },
  { id: 5, name: 'Diğer Yağlı Tohumlar', description: 'Keten tohumu ve çiğit', productIds: ['keten-tohumu', 'cigit'] },
  { id: 6, name: 'Sert Kabuklu Yağlılar', description: 'Yer fıstığı ve fındık', productIds: ['yer-fistigi', 'findik'] },
  { id: 7, name: 'Temel Endüstriyel Bitkiler', description: 'Pamuk ve kenevir', productIds: ['pamuk', 'kenevir'] },
  { id: 8, name: 'Özel Endüstriyel Bitkiler', description: 'Haşhaş ve şerbetçiotu', productIds: ['hashas', 'serbetciotu'] },
  { id: 9, name: 'Kaba Yem Bitkileri', description: 'Korunga, fiğ ve silajlık mısır', productIds: ['korunga', 'fig', 'silajlik-misir'] },
  { id: 10, name: 'Diğer Yem ve Yumru Kökler', description: 'Sorgum, yemlik pancar ve yer elması', productIds: ['sorgum', 'yemlik-pancar', 'yer-elmasi'] },
  { id: 11, name: 'Temel Kök Sebzeler', description: 'Patates, kuru soğan ve sarımsak', productIds: ['patates', 'kuru-sogan', 'sarimsak'] },
  { id: 12, name: 'Meyvesi Yenen Sebzeler', description: 'Domates, biber, patlıcan, salatalık ve kabak', productIds: ['domates', 'sivri-biber', 'patlican', 'salatalik', 'kabak'] },
  { id: 13, name: 'Yapraklı Sebzeler', description: 'Marul, ıspanak, lahana, pırasa ve pazı', productIds: ['marul', 'ispanak', 'lahana', 'pirasa', 'pazi'] },
  { id: 14, name: 'Yumuşak ve Sert Çekirdekli Meyveler', description: 'Çekirdekli meyveler ve zeytin', productIds: ['elma', 'armut', 'ayva', 'kayisi', 'seftali', 'kiraz', 'visne', 'erik', 'zeytin'] },
  { id: 15, name: 'Narenciye, Bağ ve Diğer Meyveler', description: 'Narenciye, bağ, kuruyemiş ve aromatik bitkiler', productIds: ['portakal', 'mandalina', 'limon', 'greyfurt', 'uzum', 'cilek', 'incir', 'dut', 'nar', 'ceviz', 'badem', 'antep-fistigi', 'kestane', 'kekik', 'lavanta', 'nane', 'kimyon', 'anason', 'rezene', 'biberiye'] },
  { id: 16, name: 'Canlı Hayvanlar', description: 'Büyükbaş, küçükbaş ve kümes hayvanları', productIds: ['canlihayvan'] },
  { id: 17, name: 'Et ve Et Ürünleri', description: 'Kırmızı et, beyaz et ve sakatatlar', productIds: ['kirmizi-et'] },
  { id: 18, name: 'Süt ve Süt Ürünleri', description: 'Çiğ süt, peynir, tereyağı ve yoğurt', productIds: ['sut'] },
  { id: 19, name: 'Kümes Hayvancılığı Ürünleri', description: 'Yumurta ve tüy', productIds: ['yumurta'] },
  { id: 20, name: 'Arıcılık Ürünleri', description: 'Bal, balmumu, polen, arı sütü ve propolis', productIds: ['bal'] },
  { id: 21, name: 'İpek Böcekçiliği', description: 'Yaş ipek kozası', productIds: ['yas-pek'] },
  { id: 22, name: 'Deniz Balıkları', description: 'Hamsi, istavrit ve palamut', productIds: ['hamsi'] },
  { id: 23, name: 'İç Su Balıkları', description: 'Alabalık ve sazan', productIds: ['alabalik'] },
  { id: 24, name: 'Kabuklu ve Yumuşakçalar', description: 'Karides, midye ve ıstakoz', productIds: ['karides'] },
  { id: 25, name: 'Odunsu Orman Ürünleri', description: 'Tomruk, kereste ve maden direği', productIds: ['kereste'] },
  { id: 26, name: 'Odun Dışı Orman Ürünleri', description: 'Reçine, sığla yağı ve çam fıstığı', productIds: ['cam-fistigi'] },
  { id: 27, name: 'Lifler ve Yapağılar', description: 'Yün, kıl, tiftik ve pamuk lifi', productIds: ['yun'] },
  { id: 28, name: 'Ham Deriler', description: 'Büyükbaş ve küçükbaş hayvan derileri', productIds: ['ham-deri'] },
  { id: 29, name: 'Hububat Mamulleri', description: 'Un, kepek, irmik, bulgur ve nişasta', productIds: ['un' , 'yulaf-ezmesi','misir-gevregi','tarhana','kuskus','bulgur','irmik',] },
  { id: 30, name: 'Bitkisel Yağlar', description: 'Ayçiçek yağı, zeytinyağı ve mısırözü yağı', productIds: ['aycicek-yagi', 'zeytinyagi'] },
  { id: 31, name: 'Küspeler ve Pirina', description: 'Yağ çıkarma artıkları', productIds: ['ayci-kuspesi'] },
  { id: 32, name: 'Mantarlar', description: 'Fungikültür ürünleri', productIds: ['kultur-mantari','istiridye-mantari','sitaki-aslan-yelesi-mantari','kral-istiridye-mantari','kestane-mantari',] },
  { id: 33, name: 'Tarımsal Yan Ürünler ve Atıklar', description: 'Sap, saman ve tarımsal atıklar', productIds: ['sap-saman','aniz-saman','misir-somegi-sapi','pamuk-copu-telef','budama-artiklari','aycicegi-kafasi','zeytin-prinasi','zeytin-karasuyu','seker-pancari-kuspesi','melas','meyve-sebze-posasi','findik-ceviz-kabugu','celtik-kavuzu','pirinc-kepegi','meyve-cekirdekleri','kakao-kahve-kabuklari',] },
  { id: 34, name: 'Tohumluk ve Fidan', description: 'Sertifikalı tohum ve fidan grubu', productIds: ['sertifikali-tohum','mavi-sertifikali-fidan','aronya-yaban-mersini-fidani','ejder-meyvesi-celigi','truf-asili-mese-fidani','tuplu-avokado-fidani','kinoa-karabugday-tohumlugu','tibbi-papatya-lavanta-tohumu','yerli-atalik-tohum','yem-bitkileri-tohumlugu','mikroyesillik-tohumlari',] },
  { id: 35, name: 'Yeni Nesil ve Alternatif Tarım', description: 'Spirulina ve alternatif ürünler', productIds: ['spirulina','amarant','chia-tohumu','teff','karabugday','kinoa',] },
];

export const activeProductGroupId = 0;
export const activeGroupProducts = commodities.filter((commodity) =>
  productGroups.some((group) => group.productIds.includes(commodity.id)),
);

// ── Bölgesel Arz-Talep ────────────────────────────────────────
// Bölgesel arz-talep verisi artık 81 ili kapsıyor — provinces.ts'den geliyor
export { provinces81 as regionSupply } from '@/lib/provinces';
export { allProvinceProducts } from '@/lib/provinces';

// ── Screener akıllı filtre seçenekleri ────────────────────────
export interface ScreenFilter {
  id: string;
  label: string;
  description: string;
  predicate: (c: Commodity) => boolean;
}

export const screenFilters: ScreenFilter[] = [
  {
    id: 'high-roe',
    label: 'Yüksek özkaynak kârlılığı',
    description: 'Kârlılık oranı 1.40 ve üzeri ürünler',
    predicate: (c) => c.profitabilityRatio >= 1.4,
  },
  {
    id: 'low-cost-rise',
    label: 'En az maliyet artışı',
    description: 'Aylık değişim %3 altında olanlar',
    predicate: (c) => Math.abs(c.changeMonth) < 3,
  },
  {
    id: 'high-yield',
    label: 'Yüksek verim',
    description: 'Verimlilik skoru 75 ve üzeri',
    predicate: (c) => c.efficiencyScore >= 75,
  },
  {
    id: 'rising-demand',
    label: 'Artan talep / fiyat',
    description: 'Son hafta pozitif seyredenler',
    predicate: (c) => c.changeWeek > 0,
  },
  {
    id: 'cost-stable',
    label: 'Maliyet istikrarlı',
    description: 'Son 12 ay volatilitesi düşük',
    predicate: (c) => {
      const h = c.history.slice(-12);
      const avg = h.reduce((a, b) => a + b, 0) / h.length;
      const vol = Math.sqrt(h.reduce((a, b) => a + (b - avg) ** 2, 0) / h.length);
      return (vol / avg) * 100 < 5;
    },
  },
];

export { changeFrom };

export const taSymbols: TaSymbol[] = [
  ...commodities.map((c) => ({
    id: c.id,
    name: c.name,
    category: c.category,
    unit: c.unit,
    candles: makeCandles(hashIdToSeed(c.id), 180, c.price, c.price * 0.04),
  })),
  ...indexMetrics.map((idx) => ({
    id: idx.id,
    name: idx.name,
    category: 'Endeks',
    unit: idx.unit,
    candles: makeCandles(
      idx.id.length * 7 + 200,
      180,
      idx.value / 10,
      idx.value * 0.015,
    ),
  })),
];
